/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class BinInterface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BinInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BinInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_BinInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int tick() {
    return RetroshareJNI.BinInterface_tick(swigCPtr, this);
  }

  public int senddata(SWIGTYPE_p_void data, int len) {
    return RetroshareJNI.BinInterface_senddata(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), len);
  }

  public int readdata(SWIGTYPE_p_void data, int len) {
    return RetroshareJNI.BinInterface_readdata(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), len);
  }

  public int netstatus() {
    return RetroshareJNI.BinInterface_netstatus(swigCPtr, this);
  }

  public int isactive() {
    return RetroshareJNI.BinInterface_isactive(swigCPtr, this);
  }

  public boolean moretoread() {
    return RetroshareJNI.BinInterface_moretoread(swigCPtr, this);
  }

  public boolean cansend() {
    return RetroshareJNI.BinInterface_cansend(swigCPtr, this);
  }

  public int close() {
    return RetroshareJNI.BinInterface_close(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string gethash() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.BinInterface_gethash(swigCPtr, this), true);
  }

  public java.math.BigInteger bytecount() {
    return RetroshareJNI.BinInterface_bytecount(swigCPtr, this);
  }

  public boolean bandwidthLimited() {
    return RetroshareJNI.BinInterface_bandwidthLimited(swigCPtr, this);
  }

}
