/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class BwCtrlData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BwCtrlData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BwCtrlData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_BwCtrlData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BwCtrlData() {
    this(RetroshareJNI.new_BwCtrlData(), true);
  }

  public void setMRates(RsBwRates value) {
    RetroshareJNI.BwCtrlData_mRates_set(swigCPtr, this, RsBwRates.getCPtr(value), value);
  }

  public RsBwRates getMRates() {
    long cPtr = RetroshareJNI.BwCtrlData_mRates_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsBwRates(cPtr, false);
  }

  public void setMRateUpdateTs(SWIGTYPE_p_time_t value) {
    RetroshareJNI.BwCtrlData_mRateUpdateTs_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMRateUpdateTs() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.BwCtrlData_mRateUpdateTs_get(swigCPtr, this), true);
  }

  public void setMAllocated(long value) {
    RetroshareJNI.BwCtrlData_mAllocated_set(swigCPtr, this, value);
  }

  public long getMAllocated() {
    return RetroshareJNI.BwCtrlData_mAllocated_get(swigCPtr, this);
  }

  public void setMLastSend(SWIGTYPE_p_time_t value) {
    RetroshareJNI.BwCtrlData_mLastSend_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMLastSend() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.BwCtrlData_mLastSend_get(swigCPtr, this), true);
  }

  public void setMAllowedOut(long value) {
    RetroshareJNI.BwCtrlData_mAllowedOut_set(swigCPtr, this, value);
  }

  public long getMAllowedOut() {
    return RetroshareJNI.BwCtrlData_mAllowedOut_get(swigCPtr, this);
  }

  public void setMLastRecvd(SWIGTYPE_p_time_t value) {
    RetroshareJNI.BwCtrlData_mLastRecvd_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMLastRecvd() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.BwCtrlData_mLastRecvd_get(swigCPtr, this), true);
  }

}
