/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class ChannelInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ChannelInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_ChannelInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChannelInfo() {
    this(RetroshareJNI.new_ChannelInfo(), true);
  }

  public void setChannelId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.ChannelInfo_channelId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getChannelId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.ChannelInfo_channelId_get(swigCPtr, this), true);
  }

  public void setChannelName(SWIGTYPE_p_std__wstring value) {
    RetroshareJNI.ChannelInfo_channelName_set(swigCPtr, this, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getChannelName() {
    return new SWIGTYPE_p_std__wstring(RetroshareJNI.ChannelInfo_channelName_get(swigCPtr, this), true);
  }

  public void setChannelDesc(SWIGTYPE_p_std__wstring value) {
    RetroshareJNI.ChannelInfo_channelDesc_set(swigCPtr, this, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getChannelDesc() {
    return new SWIGTYPE_p_std__wstring(RetroshareJNI.ChannelInfo_channelDesc_get(swigCPtr, this), true);
  }

  public void setChannelFlags(long value) {
    RetroshareJNI.ChannelInfo_channelFlags_set(swigCPtr, this, value);
  }

  public long getChannelFlags() {
    return RetroshareJNI.ChannelInfo_channelFlags_get(swigCPtr, this);
  }

  public void setPop(long value) {
    RetroshareJNI.ChannelInfo_pop_set(swigCPtr, this, value);
  }

  public long getPop() {
    return RetroshareJNI.ChannelInfo_pop_get(swigCPtr, this);
  }

  public void setAutoDownload(boolean value) {
    RetroshareJNI.ChannelInfo_autoDownload_set(swigCPtr, this, value);
  }

  public boolean getAutoDownload() {
    return RetroshareJNI.ChannelInfo_autoDownload_get(swigCPtr, this);
  }

  public void setPngChanImage(SWIGTYPE_p_unsigned_char value) {
    RetroshareJNI.ChannelInfo_pngChanImage_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getPngChanImage() {
    long cPtr = RetroshareJNI.ChannelInfo_pngChanImage_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setPngImageLen(long value) {
    RetroshareJNI.ChannelInfo_pngImageLen_set(swigCPtr, this, value);
  }

  public long getPngImageLen() {
    return RetroshareJNI.ChannelInfo_pngImageLen_get(swigCPtr, this);
  }

  public void setLastPost(SWIGTYPE_p_time_t value) {
    RetroshareJNI.ChannelInfo_lastPost_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getLastPost() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.ChannelInfo_lastPost_get(swigCPtr, this), true);
  }

  public void setDestination_directory(SWIGTYPE_p_std__string value) {
    RetroshareJNI.ChannelInfo_destination_directory_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getDestination_directory() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.ChannelInfo_destination_directory_get(swigCPtr, this), true);
  }

}
