/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class ChatInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ChatInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChatInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_ChatInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRsid(SWIGTYPE_p_std__string value) {
    RetroshareJNI.ChatInfo_rsid_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getRsid() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.ChatInfo_rsid_get(swigCPtr, this), true);
  }

  public void setPeer_nickname(SWIGTYPE_p_std__string value) {
    RetroshareJNI.ChatInfo_peer_nickname_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getPeer_nickname() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.ChatInfo_peer_nickname_get(swigCPtr, this), true);
  }

  public void setChatflags(long value) {
    RetroshareJNI.ChatInfo_chatflags_set(swigCPtr, this, value);
  }

  public long getChatflags() {
    return RetroshareJNI.ChatInfo_chatflags_get(swigCPtr, this);
  }

  public void setSendTime(long value) {
    RetroshareJNI.ChatInfo_sendTime_set(swigCPtr, this, value);
  }

  public long getSendTime() {
    return RetroshareJNI.ChatInfo_sendTime_get(swigCPtr, this);
  }

  public void setRecvTime(long value) {
    RetroshareJNI.ChatInfo_recvTime_set(swigCPtr, this, value);
  }

  public long getRecvTime() {
    return RetroshareJNI.ChatInfo_recvTime_get(swigCPtr, this);
  }

  public void setMsg(SWIGTYPE_p_std__wstring value) {
    RetroshareJNI.ChatInfo_msg_set(swigCPtr, this, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getMsg() {
    return new SWIGTYPE_p_std__wstring(RetroshareJNI.ChatInfo_msg_get(swigCPtr, this), true);
  }

  public ChatInfo() {
    this(RetroshareJNI.new_ChatInfo(), true);
  }

}
