/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class ChatLobbyInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ChatLobbyInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChatLobbyInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_ChatLobbyInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLobby_id(java.math.BigInteger value) {
    RetroshareJNI.ChatLobbyInfo_lobby_id_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getLobby_id() {
    return RetroshareJNI.ChatLobbyInfo_lobby_id_get(swigCPtr, this);
  }

  public void setLobby_name(SWIGTYPE_p_std__string value) {
    RetroshareJNI.ChatLobbyInfo_lobby_name_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getLobby_name() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.ChatLobbyInfo_lobby_name_get(swigCPtr, this), true);
  }

  public void setLobby_topic(SWIGTYPE_p_std__string value) {
    RetroshareJNI.ChatLobbyInfo_lobby_topic_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getLobby_topic() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.ChatLobbyInfo_lobby_topic_get(swigCPtr, this), true);
  }

  public void setParticipating_friends(SWIGTYPE_p_std__setT_std__string_t value) {
    RetroshareJNI.ChatLobbyInfo_participating_friends_set(swigCPtr, this, SWIGTYPE_p_std__setT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__setT_std__string_t getParticipating_friends() {
    return new SWIGTYPE_p_std__setT_std__string_t(RetroshareJNI.ChatLobbyInfo_participating_friends_get(swigCPtr, this), true);
  }

  public void setNick_name(SWIGTYPE_p_std__string value) {
    RetroshareJNI.ChatLobbyInfo_nick_name_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getNick_name() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.ChatLobbyInfo_nick_name_get(swigCPtr, this), true);
  }

  public void setLobby_privacy_level(long value) {
    RetroshareJNI.ChatLobbyInfo_lobby_privacy_level_set(swigCPtr, this, value);
  }

  public long getLobby_privacy_level() {
    return RetroshareJNI.ChatLobbyInfo_lobby_privacy_level_get(swigCPtr, this);
  }

  public void setNick_names(SWIGTYPE_p_std__mapT_std__string_time_t_t value) {
    RetroshareJNI.ChatLobbyInfo_nick_names_set(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_time_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__mapT_std__string_time_t_t getNick_names() {
    return new SWIGTYPE_p_std__mapT_std__string_time_t_t(RetroshareJNI.ChatLobbyInfo_nick_names_get(swigCPtr, this), true);
  }

  public void setLast_activity(SWIGTYPE_p_time_t value) {
    RetroshareJNI.ChatLobbyInfo_last_activity_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getLast_activity() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.ChatLobbyInfo_last_activity_get(swigCPtr, this), true);
  }

  public ChatLobbyInfo() {
    this(RetroshareJNI.new_ChatLobbyInfo(), true);
  }

}
