/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class CUPnPArgumentValue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CUPnPArgumentValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CUPnPArgumentValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_CUPnPArgumentValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CUPnPArgumentValue() {
    this(RetroshareJNI.new_CUPnPArgumentValue__SWIG_0(), true);
  }

  public CUPnPArgumentValue(SWIGTYPE_p_std__string argument, SWIGTYPE_p_std__string value) {
    this(RetroshareJNI.new_CUPnPArgumentValue__SWIG_1(SWIGTYPE_p_std__string.getCPtr(argument), SWIGTYPE_p_std__string.getCPtr(value)), true);
  }

  public SWIGTYPE_p_std__string GetArgument() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.CUPnPArgumentValue_GetArgument(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__string GetValue() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.CUPnPArgumentValue_GetValue(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__string SetArgument(SWIGTYPE_p_std__string argument) {
    return new SWIGTYPE_p_std__string(RetroshareJNI.CUPnPArgumentValue_SetArgument(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(argument)), false);
  }

  public SWIGTYPE_p_std__string SetValue(SWIGTYPE_p_std__string value) {
    return new SWIGTYPE_p_std__string(RetroshareJNI.CUPnPArgumentValue_SetValue(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value)), false);
  }

}
