/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class DhtPeerDetails {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DhtPeerDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DhtPeerDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_DhtPeerDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DhtPeerDetails() {
    this(RetroshareJNI.new_DhtPeerDetails(), true);
  }

  public void setMPeerType(long value) {
    RetroshareJNI.DhtPeerDetails_mPeerType_set(swigCPtr, this, value);
  }

  public long getMPeerType() {
    return RetroshareJNI.DhtPeerDetails_mPeerType_get(swigCPtr, this);
  }

  public void setMDhtId(SWIGTYPE_p_bdId value) {
    RetroshareJNI.DhtPeerDetails_mDhtId_set(swigCPtr, this, SWIGTYPE_p_bdId.getCPtr(value));
  }

  public SWIGTYPE_p_bdId getMDhtId() {
    return new SWIGTYPE_p_bdId(RetroshareJNI.DhtPeerDetails_mDhtId_get(swigCPtr, this), true);
  }

  public void setMRsId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.DhtPeerDetails_mRsId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMRsId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.DhtPeerDetails_mRsId_get(swigCPtr, this), true);
  }

  public void setMDhtState(long value) {
    RetroshareJNI.DhtPeerDetails_mDhtState_set(swigCPtr, this, value);
  }

  public long getMDhtState() {
    return RetroshareJNI.DhtPeerDetails_mDhtState_get(swigCPtr, this);
  }

  public void setMDhtUpdateTS(SWIGTYPE_p_time_t value) {
    RetroshareJNI.DhtPeerDetails_mDhtUpdateTS_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMDhtUpdateTS() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.DhtPeerDetails_mDhtUpdateTS_get(swigCPtr, this), true);
  }

  public void setMConnectLogic(PeerConnectStateBox value) {
    RetroshareJNI.DhtPeerDetails_mConnectLogic_set(swigCPtr, this, PeerConnectStateBox.getCPtr(value), value);
  }

  public PeerConnectStateBox getMConnectLogic() {
    long cPtr = RetroshareJNI.DhtPeerDetails_mConnectLogic_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PeerConnectStateBox(cPtr, false);
  }

  public void setMPeerConnectState(long value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectState_set(swigCPtr, this, value);
  }

  public long getMPeerConnectState() {
    return RetroshareJNI.DhtPeerDetails_mPeerConnectState_get(swigCPtr, this);
  }

  public void setMPeerConnectMsg(SWIGTYPE_p_std__string value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectMsg_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMPeerConnectMsg() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.DhtPeerDetails_mPeerConnectMsg_get(swigCPtr, this), true);
  }

  public void setMPeerConnectMode(long value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectMode_set(swigCPtr, this, value);
  }

  public long getMPeerConnectMode() {
    return RetroshareJNI.DhtPeerDetails_mPeerConnectMode_get(swigCPtr, this);
  }

  public void setMPeerConnectPeerId(SWIGTYPE_p_bdId value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectPeerId_set(swigCPtr, this, SWIGTYPE_p_bdId.getCPtr(value));
  }

  public SWIGTYPE_p_bdId getMPeerConnectPeerId() {
    return new SWIGTYPE_p_bdId(RetroshareJNI.DhtPeerDetails_mPeerConnectPeerId_get(swigCPtr, this), true);
  }

  public void setMPeerConnectProxyId(SWIGTYPE_p_bdId value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectProxyId_set(swigCPtr, this, SWIGTYPE_p_bdId.getCPtr(value));
  }

  public SWIGTYPE_p_bdId getMPeerConnectProxyId() {
    return new SWIGTYPE_p_bdId(RetroshareJNI.DhtPeerDetails_mPeerConnectProxyId_get(swigCPtr, this), true);
  }

  public void setMPeerConnectAddr(SWIGTYPE_p_sockaddr_in value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectAddr_set(swigCPtr, this, SWIGTYPE_p_sockaddr_in.getCPtr(value));
  }

  public SWIGTYPE_p_sockaddr_in getMPeerConnectAddr() {
    return new SWIGTYPE_p_sockaddr_in(RetroshareJNI.DhtPeerDetails_mPeerConnectAddr_get(swigCPtr, this), true);
  }

  public void setMPeerConnectPoint(long value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectPoint_set(swigCPtr, this, value);
  }

  public long getMPeerConnectPoint() {
    return RetroshareJNI.DhtPeerDetails_mPeerConnectPoint_get(swigCPtr, this);
  }

  public void setMPeerConnectUdpTS(SWIGTYPE_p_time_t value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectUdpTS_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMPeerConnectUdpTS() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.DhtPeerDetails_mPeerConnectUdpTS_get(swigCPtr, this), true);
  }

  public void setMPeerConnectTS(SWIGTYPE_p_time_t value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectTS_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMPeerConnectTS() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.DhtPeerDetails_mPeerConnectTS_get(swigCPtr, this), true);
  }

  public void setMPeerConnectClosedTS(SWIGTYPE_p_time_t value) {
    RetroshareJNI.DhtPeerDetails_mPeerConnectClosedTS_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMPeerConnectClosedTS() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.DhtPeerDetails_mPeerConnectClosedTS_get(swigCPtr, this), true);
  }

  public void setMExclusiveProxyLock(boolean value) {
    RetroshareJNI.DhtPeerDetails_mExclusiveProxyLock_set(swigCPtr, this, value);
  }

  public boolean getMExclusiveProxyLock() {
    return RetroshareJNI.DhtPeerDetails_mExclusiveProxyLock_get(swigCPtr, this);
  }

  public void setMPeerReqStatusMsg(SWIGTYPE_p_std__string value) {
    RetroshareJNI.DhtPeerDetails_mPeerReqStatusMsg_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMPeerReqStatusMsg() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.DhtPeerDetails_mPeerReqStatusMsg_get(swigCPtr, this), true);
  }

  public void setMPeerReqState(long value) {
    RetroshareJNI.DhtPeerDetails_mPeerReqState_set(swigCPtr, this, value);
  }

  public long getMPeerReqState() {
    return RetroshareJNI.DhtPeerDetails_mPeerReqState_get(swigCPtr, this);
  }

  public void setMPeerReqMode(long value) {
    RetroshareJNI.DhtPeerDetails_mPeerReqMode_set(swigCPtr, this, value);
  }

  public long getMPeerReqMode() {
    return RetroshareJNI.DhtPeerDetails_mPeerReqMode_get(swigCPtr, this);
  }

  public void setMPeerReqProxyId(SWIGTYPE_p_bdId value) {
    RetroshareJNI.DhtPeerDetails_mPeerReqProxyId_set(swigCPtr, this, SWIGTYPE_p_bdId.getCPtr(value));
  }

  public SWIGTYPE_p_bdId getMPeerReqProxyId() {
    return new SWIGTYPE_p_bdId(RetroshareJNI.DhtPeerDetails_mPeerReqProxyId_get(swigCPtr, this), true);
  }

  public void setMPeerReqTS(SWIGTYPE_p_time_t value) {
    RetroshareJNI.DhtPeerDetails_mPeerReqTS_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMPeerReqTS() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.DhtPeerDetails_mPeerReqTS_get(swigCPtr, this), true);
  }

  public void setMPeerCbMsg(SWIGTYPE_p_std__string value) {
    RetroshareJNI.DhtPeerDetails_mPeerCbMsg_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMPeerCbMsg() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.DhtPeerDetails_mPeerCbMsg_get(swigCPtr, this), true);
  }

  public void setMPeerCbMode(long value) {
    RetroshareJNI.DhtPeerDetails_mPeerCbMode_set(swigCPtr, this, value);
  }

  public long getMPeerCbMode() {
    return RetroshareJNI.DhtPeerDetails_mPeerCbMode_get(swigCPtr, this);
  }

  public void setMPeerCbPoint(long value) {
    RetroshareJNI.DhtPeerDetails_mPeerCbPoint_set(swigCPtr, this, value);
  }

  public long getMPeerCbPoint() {
    return RetroshareJNI.DhtPeerDetails_mPeerCbPoint_get(swigCPtr, this);
  }

  public void setMPeerCbProxyId(SWIGTYPE_p_bdId value) {
    RetroshareJNI.DhtPeerDetails_mPeerCbProxyId_set(swigCPtr, this, SWIGTYPE_p_bdId.getCPtr(value));
  }

  public SWIGTYPE_p_bdId getMPeerCbProxyId() {
    return new SWIGTYPE_p_bdId(RetroshareJNI.DhtPeerDetails_mPeerCbProxyId_get(swigCPtr, this), true);
  }

  public void setMPeerCbDestId(SWIGTYPE_p_bdId value) {
    RetroshareJNI.DhtPeerDetails_mPeerCbDestId_set(swigCPtr, this, SWIGTYPE_p_bdId.getCPtr(value));
  }

  public SWIGTYPE_p_bdId getMPeerCbDestId() {
    return new SWIGTYPE_p_bdId(RetroshareJNI.DhtPeerDetails_mPeerCbDestId_get(swigCPtr, this), true);
  }

  public void setMPeerCbTS(SWIGTYPE_p_time_t value) {
    RetroshareJNI.DhtPeerDetails_mPeerCbTS_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMPeerCbTS() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.DhtPeerDetails_mPeerCbTS_get(swigCPtr, this), true);
  }

}
