/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class dhtPeerEntry {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dhtPeerEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dhtPeerEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_dhtPeerEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public dhtPeerEntry() {
    this(RetroshareJNI.new_dhtPeerEntry(), true);
  }

  public void setId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.dhtPeerEntry_id_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.dhtPeerEntry_id_get(swigCPtr, this), true);
  }

  public void setState(long value) {
    RetroshareJNI.dhtPeerEntry_state_set(swigCPtr, this, value);
  }

  public long getState() {
    return RetroshareJNI.dhtPeerEntry_state_get(swigCPtr, this);
  }

  public void setLastTS(SWIGTYPE_p_time_t value) {
    RetroshareJNI.dhtPeerEntry_lastTS_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getLastTS() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.dhtPeerEntry_lastTS_get(swigCPtr, this), true);
  }

  public void setNotifyPending(long value) {
    RetroshareJNI.dhtPeerEntry_notifyPending_set(swigCPtr, this, value);
  }

  public long getNotifyPending() {
    return RetroshareJNI.dhtPeerEntry_notifyPending_get(swigCPtr, this);
  }

  public void setNotifyTS(SWIGTYPE_p_time_t value) {
    RetroshareJNI.dhtPeerEntry_notifyTS_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getNotifyTS() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.dhtPeerEntry_notifyTS_get(swigCPtr, this), true);
  }

  public void setLaddr(SWIGTYPE_p_sockaddr_in value) {
    RetroshareJNI.dhtPeerEntry_laddr_set(swigCPtr, this, SWIGTYPE_p_sockaddr_in.getCPtr(value));
  }

  public SWIGTYPE_p_sockaddr_in getLaddr() {
    return new SWIGTYPE_p_sockaddr_in(RetroshareJNI.dhtPeerEntry_laddr_get(swigCPtr, this), true);
  }

  public void setRaddr(SWIGTYPE_p_sockaddr_in value) {
    RetroshareJNI.dhtPeerEntry_raddr_set(swigCPtr, this, SWIGTYPE_p_sockaddr_in.getCPtr(value));
  }

  public SWIGTYPE_p_sockaddr_in getRaddr() {
    return new SWIGTYPE_p_sockaddr_in(RetroshareJNI.dhtPeerEntry_raddr_get(swigCPtr, this), true);
  }

  public void setType(long value) {
    RetroshareJNI.dhtPeerEntry_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return RetroshareJNI.dhtPeerEntry_type_get(swigCPtr, this);
  }

  public void setHash1(SWIGTYPE_p_std__string value) {
    RetroshareJNI.dhtPeerEntry_hash1_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getHash1() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.dhtPeerEntry_hash1_get(swigCPtr, this), true);
  }

  public void setHash2(SWIGTYPE_p_std__string value) {
    RetroshareJNI.dhtPeerEntry_hash2_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getHash2() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.dhtPeerEntry_hash2_get(swigCPtr, this), true);
  }

}
