/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class DistantChatInviteInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DistantChatInviteInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DistantChatInviteInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_DistantChatInviteInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHash(SWIGTYPE_p_std__string value) {
    RetroshareJNI.DistantChatInviteInfo_hash_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getHash() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.DistantChatInviteInfo_hash_get(swigCPtr, this), true);
  }

  public void setEncrypted_radix64_string(SWIGTYPE_p_std__string value) {
    RetroshareJNI.DistantChatInviteInfo_encrypted_radix64_string_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getEncrypted_radix64_string() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.DistantChatInviteInfo_encrypted_radix64_string_get(swigCPtr, this), true);
  }

  public void setDestination_pgp_id(SWIGTYPE_p_std__string value) {
    RetroshareJNI.DistantChatInviteInfo_destination_pgp_id_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getDestination_pgp_id() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.DistantChatInviteInfo_destination_pgp_id_get(swigCPtr, this), true);
  }

  public void setTime_of_validity(SWIGTYPE_p_time_t value) {
    RetroshareJNI.DistantChatInviteInfo_time_of_validity_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getTime_of_validity() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.DistantChatInviteInfo_time_of_validity_get(swigCPtr, this), true);
  }

  public void setInvite_flags(long value) {
    RetroshareJNI.DistantChatInviteInfo_invite_flags_set(swigCPtr, this, value);
  }

  public long getInvite_flags() {
    return RetroshareJNI.DistantChatInviteInfo_invite_flags_get(swigCPtr, this);
  }

  public DistantChatInviteInfo() {
    this(RetroshareJNI.new_DistantChatInviteInfo(), true);
  }

}
