/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class ftFileStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ftFileStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ftFileStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_ftFileStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ftFileStatus() {
    this(RetroshareJNI.new_ftFileStatus__SWIG_0(), true);
  }

  public ftFileStatus(SWIGTYPE_p_std__string hash_in) {
    this(RetroshareJNI.new_ftFileStatus__SWIG_1(SWIGTYPE_p_std__string.getCPtr(hash_in)), true);
  }

  public void setHash(SWIGTYPE_p_std__string value) {
    RetroshareJNI.ftFileStatus_hash_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getHash() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.ftFileStatus_hash_get(swigCPtr, this), true);
  }

  public void setStat(ftFileStatus.Status value) {
    RetroshareJNI.ftFileStatus_stat_set(swigCPtr, this, value.swigValue());
  }

  public ftFileStatus.Status getStat() {
    return ftFileStatus.Status.swigToEnum(RetroshareJNI.ftFileStatus_stat_get(swigCPtr, this));
  }

  public final static class Status {
    public final static ftFileStatus.Status PQIFILE_INIT = new ftFileStatus.Status("PQIFILE_INIT");
    public final static ftFileStatus.Status PQIFILE_NOT_ONLINE = new ftFileStatus.Status("PQIFILE_NOT_ONLINE");
    public final static ftFileStatus.Status PQIFILE_DOWNLOADING = new ftFileStatus.Status("PQIFILE_DOWNLOADING");
    public final static ftFileStatus.Status PQIFILE_COMPLETE = new ftFileStatus.Status("PQIFILE_COMPLETE");
    public final static ftFileStatus.Status PQIFILE_CHECKING = new ftFileStatus.Status("PQIFILE_CHECKING");
    public final static ftFileStatus.Status PQIFILE_FAIL = new ftFileStatus.Status("PQIFILE_FAIL");
    public final static ftFileStatus.Status PQIFILE_FAIL_CANCEL = new ftFileStatus.Status("PQIFILE_FAIL_CANCEL");
    public final static ftFileStatus.Status PQIFILE_FAIL_NOT_AVAIL = new ftFileStatus.Status("PQIFILE_FAIL_NOT_AVAIL");
    public final static ftFileStatus.Status PQIFILE_FAIL_NOT_OPEN = new ftFileStatus.Status("PQIFILE_FAIL_NOT_OPEN");
    public final static ftFileStatus.Status PQIFILE_FAIL_NOT_SEEK = new ftFileStatus.Status("PQIFILE_FAIL_NOT_SEEK");
    public final static ftFileStatus.Status PQIFILE_FAIL_NOT_WRITE = new ftFileStatus.Status("PQIFILE_FAIL_NOT_WRITE");
    public final static ftFileStatus.Status PQIFILE_FAIL_NOT_READ = new ftFileStatus.Status("PQIFILE_FAIL_NOT_READ");
    public final static ftFileStatus.Status PQIFILE_FAIL_BAD_PATH = new ftFileStatus.Status("PQIFILE_FAIL_BAD_PATH");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Status swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Status.class + " with value " + swigValue);
    }

    private Status(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Status(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Status(String swigName, Status swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Status[] swigValues = { PQIFILE_INIT, PQIFILE_NOT_ONLINE, PQIFILE_DOWNLOADING, PQIFILE_COMPLETE, PQIFILE_CHECKING, PQIFILE_FAIL, PQIFILE_FAIL_CANCEL, PQIFILE_FAIL_NOT_AVAIL, PQIFILE_FAIL_NOT_OPEN, PQIFILE_FAIL_NOT_SEEK, PQIFILE_FAIL_NOT_WRITE, PQIFILE_FAIL_NOT_READ, PQIFILE_FAIL_BAD_PATH };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
