/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class ftFileSearch extends ftSearch {
  private long swigCPtr;

  protected ftFileSearch(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.ftFileSearch_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ftFileSearch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_ftFileSearch(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ftFileSearch() {
    this(RetroshareJNI.new_ftFileSearch(), true);
  }

  public boolean addSearchMode(ftSearch search, SWIGTYPE_p_t_RsFlags32T_0xf29ba5_t hintflags) {
    return RetroshareJNI.ftFileSearch_addSearchMode(swigCPtr, this, ftSearch.getCPtr(search), search, SWIGTYPE_p_t_RsFlags32T_0xf29ba5_t.getCPtr(hintflags));
  }

  public boolean search(SWIGTYPE_p_std__string hash, SWIGTYPE_p_t_RsFlags32T_0xf29ba5_t hintflags, FileInfo info) {
    return RetroshareJNI.ftFileSearch_search(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(hash), SWIGTYPE_p_t_RsFlags32T_0xf29ba5_t.getCPtr(hintflags), FileInfo.getCPtr(info), info);
  }

}
