/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class gameStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected gameStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gameStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_gameStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setServiceId(long value) {
    RetroshareJNI.gameStatus_serviceId_set(swigCPtr, this, value);
  }

  public long getServiceId() {
    return RetroshareJNI.gameStatus_serviceId_get(swigCPtr, this);
  }

  public void setGameId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.gameStatus_gameId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getGameId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.gameStatus_gameId_get(swigCPtr, this), true);
  }

  public void setGameName(SWIGTYPE_p_std__wstring value) {
    RetroshareJNI.gameStatus_gameName_set(swigCPtr, this, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getGameName() {
    return new SWIGTYPE_p_std__wstring(RetroshareJNI.gameStatus_gameName_get(swigCPtr, this), true);
  }

  public void setAreServer(boolean value) {
    RetroshareJNI.gameStatus_areServer_set(swigCPtr, this, value);
  }

  public boolean getAreServer() {
    return RetroshareJNI.gameStatus_areServer_get(swigCPtr, this);
  }

  public void setServerId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.gameStatus_serverId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getServerId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.gameStatus_serverId_get(swigCPtr, this), true);
  }

  public void setNumPlayers(int value) {
    RetroshareJNI.gameStatus_numPlayers_set(swigCPtr, this, value);
  }

  public int getNumPlayers() {
    return RetroshareJNI.gameStatus_numPlayers_get(swigCPtr, this);
  }

  public void setAllowedPeers(SWIGTYPE_p_std__listT_std__string_t value) {
    RetroshareJNI.gameStatus_allowedPeers_set(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_std__string_t getAllowedPeers() {
    return new SWIGTYPE_p_std__listT_std__string_t(RetroshareJNI.gameStatus_allowedPeers_get(swigCPtr, this), true);
  }

  public void setInterestedPeers(SWIGTYPE_p_std__listT_std__string_t value) {
    RetroshareJNI.gameStatus_interestedPeers_set(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_std__string_t getInterestedPeers() {
    return new SWIGTYPE_p_std__listT_std__string_t(RetroshareJNI.gameStatus_interestedPeers_get(swigCPtr, this), true);
  }

  public void setPeerIds(SWIGTYPE_p_std__listT_std__string_t value) {
    RetroshareJNI.gameStatus_peerIds_set(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_std__string_t getPeerIds() {
    return new SWIGTYPE_p_std__listT_std__string_t(RetroshareJNI.gameStatus_peerIds_get(swigCPtr, this), true);
  }

  public void setState(long value) {
    RetroshareJNI.gameStatus_state_set(swigCPtr, this, value);
  }

  public long getState() {
    return RetroshareJNI.gameStatus_state_get(swigCPtr, this);
  }

  public gameStatus() {
    this(RetroshareJNI.new_gameStatus(), true);
  }

}
