/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class GroupMetaReq extends GxsRequest {
  private long swigCPtr;

  protected GroupMetaReq(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.GroupMetaReq_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GroupMetaReq obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_GroupMetaReq(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setMGroupIds(SWIGTYPE_p_std__listT_std__string_t value) {
    RetroshareJNI.GroupMetaReq_mGroupIds_set(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_std__string_t getMGroupIds() {
    return new SWIGTYPE_p_std__listT_std__string_t(RetroshareJNI.GroupMetaReq_mGroupIds_get(swigCPtr, this), true);
  }

  public void setMGroupMetaData(SWIGTYPE_p_std__listT_RsGxsGrpMetaData_p_t value) {
    RetroshareJNI.GroupMetaReq_mGroupMetaData_set(swigCPtr, this, SWIGTYPE_p_std__listT_RsGxsGrpMetaData_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_RsGxsGrpMetaData_p_t getMGroupMetaData() {
    long cPtr = RetroshareJNI.GroupMetaReq_mGroupMetaData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__listT_RsGxsGrpMetaData_p_t(cPtr, false);
  }

  public GroupMetaReq() {
    this(RetroshareJNI.new_GroupMetaReq(), true);
  }

}
