/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class GrpLocMetaData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GrpLocMetaData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GrpLocMetaData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_GrpLocMetaData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GrpLocMetaData(GrpLocMetaData meta) {
    this(RetroshareJNI.new_GrpLocMetaData__SWIG_0(GrpLocMetaData.getCPtr(meta), meta), true);
  }

  public GrpLocMetaData() {
    this(RetroshareJNI.new_GrpLocMetaData__SWIG_1(), true);
  }

  public void setGrpId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.GrpLocMetaData_grpId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getGrpId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.GrpLocMetaData_grpId_get(swigCPtr, this), true);
  }

  public void setVal(ContentValue value) {
    RetroshareJNI.GrpLocMetaData_val_set(swigCPtr, this, ContentValue.getCPtr(value), value);
  }

  public ContentValue getVal() {
    long cPtr = RetroshareJNI.GrpLocMetaData_val_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ContentValue(cPtr, false);
  }

}
