/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class GxsDataProxyVEG {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GxsDataProxyVEG(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GxsDataProxyVEG obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_GxsDataProxyVEG(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GxsDataProxyVEG() {
    this(RetroshareJNI.new_GxsDataProxyVEG(), true);
  }

  public boolean getGroupList(SWIGTYPE_p_unsigned_int token, SWIGTYPE_p_RsTokReqOptionsVEG opts, SWIGTYPE_p_std__listT_std__string_t groupIds, SWIGTYPE_p_std__listT_std__string_t outGroupIds) {
    return RetroshareJNI.GxsDataProxyVEG_getGroupList(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), SWIGTYPE_p_RsTokReqOptionsVEG.getCPtr(opts), SWIGTYPE_p_std__listT_std__string_t.getCPtr(groupIds), SWIGTYPE_p_std__listT_std__string_t.getCPtr(outGroupIds));
  }

  public boolean getMsgList(SWIGTYPE_p_unsigned_int token, SWIGTYPE_p_RsTokReqOptionsVEG opts, SWIGTYPE_p_std__listT_std__string_t groupIds, SWIGTYPE_p_std__listT_std__string_t outMsgIds) {
    return RetroshareJNI.GxsDataProxyVEG_getMsgList(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), SWIGTYPE_p_RsTokReqOptionsVEG.getCPtr(opts), SWIGTYPE_p_std__listT_std__string_t.getCPtr(groupIds), SWIGTYPE_p_std__listT_std__string_t.getCPtr(outMsgIds));
  }

  public boolean getMsgRelatedList(SWIGTYPE_p_unsigned_int token, SWIGTYPE_p_RsTokReqOptionsVEG opts, SWIGTYPE_p_std__listT_std__string_t msgIds, SWIGTYPE_p_std__listT_std__string_t outMsgIds) {
    return RetroshareJNI.GxsDataProxyVEG_getMsgRelatedList(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), SWIGTYPE_p_RsTokReqOptionsVEG.getCPtr(opts), SWIGTYPE_p_std__listT_std__string_t.getCPtr(msgIds), SWIGTYPE_p_std__listT_std__string_t.getCPtr(outMsgIds));
  }

  public boolean createGroup(SWIGTYPE_p_void groupData) {
    return RetroshareJNI.GxsDataProxyVEG_createGroup(swigCPtr, this, SWIGTYPE_p_void.getCPtr(groupData));
  }

  public boolean createMsg(SWIGTYPE_p_void msgData) {
    return RetroshareJNI.GxsDataProxyVEG_createMsg(swigCPtr, this, SWIGTYPE_p_void.getCPtr(msgData));
  }

  public boolean convertGroupToMetaData(SWIGTYPE_p_void groupData, RsGroupMetaData meta) {
    return RetroshareJNI.GxsDataProxyVEG_convertGroupToMetaData(swigCPtr, this, SWIGTYPE_p_void.getCPtr(groupData), RsGroupMetaData.getCPtr(meta), meta);
  }

  public boolean convertMsgToMetaData(SWIGTYPE_p_void groupData, RsMsgMetaData meta) {
    return RetroshareJNI.GxsDataProxyVEG_convertMsgToMetaData(swigCPtr, this, SWIGTYPE_p_void.getCPtr(groupData), RsMsgMetaData.getCPtr(meta), meta);
  }

  public boolean getGroupSummary(SWIGTYPE_p_std__listT_std__string_t groupIds, SWIGTYPE_p_std__listT_RsGroupMetaData_t groupSummary) {
    return RetroshareJNI.GxsDataProxyVEG_getGroupSummary__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(groupIds), SWIGTYPE_p_std__listT_RsGroupMetaData_t.getCPtr(groupSummary));
  }

  public boolean getMsgSummary(SWIGTYPE_p_std__listT_std__string_t msgIds, SWIGTYPE_p_std__listT_RsMsgMetaData_t msgSummary) {
    return RetroshareJNI.GxsDataProxyVEG_getMsgSummary__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(msgIds), SWIGTYPE_p_std__listT_RsMsgMetaData_t.getCPtr(msgSummary));
  }

  public boolean getGroupSummary(SWIGTYPE_p_std__string groupId, RsGroupMetaData groupSummary) {
    return RetroshareJNI.GxsDataProxyVEG_getGroupSummary__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(groupId), RsGroupMetaData.getCPtr(groupSummary), groupSummary);
  }

  public boolean getMsgSummary(SWIGTYPE_p_std__string msgId, RsMsgMetaData msgSummary) {
    return RetroshareJNI.GxsDataProxyVEG_getMsgSummary__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(msgId), RsMsgMetaData.getCPtr(msgSummary), msgSummary);
  }

  public boolean getGroupData(SWIGTYPE_p_std__string groupId, SWIGTYPE_p_p_void groupData) {
    return RetroshareJNI.GxsDataProxyVEG_getGroupData(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(groupId), SWIGTYPE_p_p_void.getCPtr(groupData));
  }

  public boolean getMsgData(SWIGTYPE_p_std__string msgId, SWIGTYPE_p_p_void msgData) {
    return RetroshareJNI.GxsDataProxyVEG_getMsgData(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(msgId), SWIGTYPE_p_p_void.getCPtr(msgData));
  }

  public boolean isUniqueGroup(SWIGTYPE_p_std__string groupId) {
    return RetroshareJNI.GxsDataProxyVEG_isUniqueGroup(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(groupId));
  }

  public boolean isUniqueMsg(SWIGTYPE_p_std__string msgId) {
    return RetroshareJNI.GxsDataProxyVEG_isUniqueMsg(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(msgId));
  }

  public boolean setMessageStatus(SWIGTYPE_p_std__string msgId, long status, long statusMask) {
    return RetroshareJNI.GxsDataProxyVEG_setMessageStatus(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(msgId), status, statusMask);
  }

  public boolean setGroupStatus(SWIGTYPE_p_std__string groupId, long status, long statusMask) {
    return RetroshareJNI.GxsDataProxyVEG_setGroupStatus(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(groupId), status, statusMask);
  }

  public boolean setGroupSubscribeFlags(SWIGTYPE_p_std__string groupId, long subscribeFlags, long subscribeMask) {
    return RetroshareJNI.GxsDataProxyVEG_setGroupSubscribeFlags(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(groupId), subscribeFlags, subscribeMask);
  }

  public boolean setMessageServiceString(SWIGTYPE_p_std__string msgId, SWIGTYPE_p_std__string str) {
    return RetroshareJNI.GxsDataProxyVEG_setMessageServiceString(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(msgId), SWIGTYPE_p_std__string.getCPtr(str));
  }

  public boolean setGroupServiceString(SWIGTYPE_p_std__string grpId, SWIGTYPE_p_std__string str) {
    return RetroshareJNI.GxsDataProxyVEG_setGroupServiceString(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(grpId), SWIGTYPE_p_std__string.getCPtr(str));
  }

}
