/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class GxsServiceStatistic {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GxsServiceStatistic(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GxsServiceStatistic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_GxsServiceStatistic(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMNumMsgs(long value) {
    RetroshareJNI.GxsServiceStatistic_mNumMsgs_set(swigCPtr, this, value);
  }

  public long getMNumMsgs() {
    return RetroshareJNI.GxsServiceStatistic_mNumMsgs_get(swigCPtr, this);
  }

  public void setMNumGrps(long value) {
    RetroshareJNI.GxsServiceStatistic_mNumGrps_set(swigCPtr, this, value);
  }

  public long getMNumGrps() {
    return RetroshareJNI.GxsServiceStatistic_mNumGrps_get(swigCPtr, this);
  }

  public void setMSizeOfMsgs(long value) {
    RetroshareJNI.GxsServiceStatistic_mSizeOfMsgs_set(swigCPtr, this, value);
  }

  public long getMSizeOfMsgs() {
    return RetroshareJNI.GxsServiceStatistic_mSizeOfMsgs_get(swigCPtr, this);
  }

  public void setMSizeOfGrps(long value) {
    RetroshareJNI.GxsServiceStatistic_mSizeOfGrps_set(swigCPtr, this, value);
  }

  public long getMSizeOfGrps() {
    return RetroshareJNI.GxsServiceStatistic_mSizeOfGrps_get(swigCPtr, this);
  }

  public void setMNumGrpsSubscribed(long value) {
    RetroshareJNI.GxsServiceStatistic_mNumGrpsSubscribed_set(swigCPtr, this, value);
  }

  public long getMNumGrpsSubscribed() {
    return RetroshareJNI.GxsServiceStatistic_mNumGrpsSubscribed_get(swigCPtr, this);
  }

  public void setMSizeStore(long value) {
    RetroshareJNI.GxsServiceStatistic_mSizeStore_set(swigCPtr, this, value);
  }

  public long getMSizeStore() {
    return RetroshareJNI.GxsServiceStatistic_mSizeStore_get(swigCPtr, this);
  }

  public GxsServiceStatistic() {
    this(RetroshareJNI.new_GxsServiceStatistic(), true);
  }

}
