/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class MsgInfoSummary {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MsgInfoSummary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MsgInfoSummary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_MsgInfoSummary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MsgInfoSummary() {
    this(RetroshareJNI.new_MsgInfoSummary(), true);
  }

  public void setMsgId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.MsgInfoSummary_msgId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMsgId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.MsgInfoSummary_msgId_get(swigCPtr, this), true);
  }

  public void setSrcId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.MsgInfoSummary_srcId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getSrcId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.MsgInfoSummary_srcId_get(swigCPtr, this), true);
  }

  public void setMsgflags(long value) {
    RetroshareJNI.MsgInfoSummary_msgflags_set(swigCPtr, this, value);
  }

  public long getMsgflags() {
    return RetroshareJNI.MsgInfoSummary_msgflags_get(swigCPtr, this);
  }

  public void setTitle(SWIGTYPE_p_std__wstring value) {
    RetroshareJNI.MsgInfoSummary_title_set(swigCPtr, this, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getTitle() {
    return new SWIGTYPE_p_std__wstring(RetroshareJNI.MsgInfoSummary_title_get(swigCPtr, this), true);
  }

  public void setCount(int value) {
    RetroshareJNI.MsgInfoSummary_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return RetroshareJNI.MsgInfoSummary_count_get(swigCPtr, this);
  }

  public void setTs(SWIGTYPE_p_time_t value) {
    RetroshareJNI.MsgInfoSummary_ts_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getTs() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.MsgInfoSummary_ts_get(swigCPtr, this), true);
  }

}
