/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class MsgLocMetaData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MsgLocMetaData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MsgLocMetaData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_MsgLocMetaData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MsgLocMetaData(MsgLocMetaData meta) {
    this(RetroshareJNI.new_MsgLocMetaData__SWIG_0(MsgLocMetaData.getCPtr(meta), meta), true);
  }

  public MsgLocMetaData() {
    this(RetroshareJNI.new_MsgLocMetaData__SWIG_1(), true);
  }

  public void setMsgId(SWIGTYPE_p_std__pairT_std__string_std__string_t value) {
    RetroshareJNI.MsgLocMetaData_msgId_set(swigCPtr, this, SWIGTYPE_p_std__pairT_std__string_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__pairT_std__string_std__string_t getMsgId() {
    return new SWIGTYPE_p_std__pairT_std__string_std__string_t(RetroshareJNI.MsgLocMetaData_msgId_get(swigCPtr, this), true);
  }

  public void setVal(ContentValue value) {
    RetroshareJNI.MsgLocMetaData_val_set(swigCPtr, this, ContentValue.getCPtr(value), value);
  }

  public ContentValue getVal() {
    long cPtr = RetroshareJNI.MsgLocMetaData_val_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ContentValue(cPtr, false);
  }

}
