/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class MsgUpdate {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MsgUpdate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MsgUpdate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_MsgUpdate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMsgId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.MsgUpdate_msgId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMsgId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.MsgUpdate_msgId_get(swigCPtr, this), true);
  }

  public void setCv(ContentValue value) {
    RetroshareJNI.MsgUpdate_cv_set(swigCPtr, this, ContentValue.getCPtr(value), value);
  }

  public ContentValue getCv() {
    long cPtr = RetroshareJNI.MsgUpdate_cv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ContentValue(cPtr, false);
  }

  public MsgUpdate() {
    this(RetroshareJNI.new_MsgUpdate(), true);
  }

}
