/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class NetInterface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NetInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NetInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_NetInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int connect(SWIGTYPE_p_sockaddr_in raddr) {
    return RetroshareJNI.NetInterface_connect(swigCPtr, this, SWIGTYPE_p_sockaddr_in.getCPtr(raddr));
  }

  public int listen() {
    return RetroshareJNI.NetInterface_listen(swigCPtr, this);
  }

  public int stoplistening() {
    return RetroshareJNI.NetInterface_stoplistening(swigCPtr, this);
  }

  public int disconnect() {
    return RetroshareJNI.NetInterface_disconnect(swigCPtr, this);
  }

  public int reset() {
    return RetroshareJNI.NetInterface_reset(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string PeerId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.NetInterface_PeerId(swigCPtr, this), true);
  }

  public int getConnectAddress(SWIGTYPE_p_sockaddr_in raddr) {
    return RetroshareJNI.NetInterface_getConnectAddress(swigCPtr, this, SWIGTYPE_p_sockaddr_in.getCPtr(raddr));
  }

  public boolean connect_parameter(long type, long value) {
    return RetroshareJNI.NetInterface_connect_parameter(swigCPtr, this, type, value);
  }

  public boolean connect_additional_address(long arg0, SWIGTYPE_p_sockaddr_in arg1) {
    return RetroshareJNI.NetInterface_connect_additional_address(swigCPtr, this, arg0, SWIGTYPE_p_sockaddr_in.getCPtr(arg1));
  }

}
