/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class NxsTransaction {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NxsTransaction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NxsTransaction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_NxsTransaction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static short getFLAG_STATE_STARTING() {
    return RetroshareJNI.NxsTransaction_FLAG_STATE_STARTING_get();
  }

  public static short getFLAG_STATE_RECEIVING() {
    return RetroshareJNI.NxsTransaction_FLAG_STATE_RECEIVING_get();
  }

  public static short getFLAG_STATE_SENDING() {
    return RetroshareJNI.NxsTransaction_FLAG_STATE_SENDING_get();
  }

  public static short getFLAG_STATE_COMPLETED() {
    return RetroshareJNI.NxsTransaction_FLAG_STATE_COMPLETED_get();
  }

  public static short getFLAG_STATE_FAILED() {
    return RetroshareJNI.NxsTransaction_FLAG_STATE_FAILED_get();
  }

  public static short getFLAG_STATE_WAITING_CONFIRM() {
    return RetroshareJNI.NxsTransaction_FLAG_STATE_WAITING_CONFIRM_get();
  }

  public NxsTransaction() {
    this(RetroshareJNI.new_NxsTransaction(), true);
  }

  public void setMFlag(long value) {
    RetroshareJNI.NxsTransaction_mFlag_set(swigCPtr, this, value);
  }

  public long getMFlag() {
    return RetroshareJNI.NxsTransaction_mFlag_get(swigCPtr, this);
  }

  public void setMTimeOut(long value) {
    RetroshareJNI.NxsTransaction_mTimeOut_set(swigCPtr, this, value);
  }

  public long getMTimeOut() {
    return RetroshareJNI.NxsTransaction_mTimeOut_get(swigCPtr, this);
  }

  public void setMTransaction(RsNxsTransac value) {
    RetroshareJNI.NxsTransaction_mTransaction_set(swigCPtr, this, RsNxsTransac.getCPtr(value), value);
  }

  public RsNxsTransac getMTransaction() {
    long cPtr = RetroshareJNI.NxsTransaction_mTransaction_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsNxsTransac(cPtr, false);
  }

  public void setMItems(SWIGTYPE_p_std__listT_RsNxsItem_p_t value) {
    RetroshareJNI.NxsTransaction_mItems_set(swigCPtr, this, SWIGTYPE_p_std__listT_RsNxsItem_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_RsNxsItem_p_t getMItems() {
    long cPtr = RetroshareJNI.NxsTransaction_mItems_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__listT_RsNxsItem_p_t(cPtr, false);
  }

}
