/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class NxsTestScenario {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NxsTestScenario(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NxsTestScenario obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_NxsTestScenario(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_std__string getTestName() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.NxsTestScenario_getTestName(swigCPtr, this), true);
  }

  public RsGeneralDataService getDataService(SWIGTYPE_p_std__string peer) {
    long cPtr = RetroshareJNI.NxsTestScenario_getDataService(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(peer));
    return (cPtr == 0) ? null : new RsGeneralDataService(cPtr, false);
  }

  public boolean testPassed() {
    return RetroshareJNI.NxsTestScenario_testPassed(swigCPtr, this);
  }

  public int getServiceType() {
    return RetroshareJNI.NxsTestScenario_getServiceType(swigCPtr, this);
  }

  public void cleanUp() {
    RetroshareJNI.NxsTestScenario_cleanUp(swigCPtr, this);
  }

}
