/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class p3GRouter extends RsGRouter {
  private long swigCPtr;

  protected p3GRouter(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.p3GRouter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(p3GRouter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_p3GRouter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public p3GRouter(p3LinkMgr lm) {
    this(RetroshareJNI.new_p3GRouter(p3LinkMgr.getCPtr(lm), lm), true);
  }

  public boolean registerClientService(long id, SWIGTYPE_p_GRouterClientService service) {
    return RetroshareJNI.p3GRouter_registerClientService(swigCPtr, this, id, SWIGTYPE_p_GRouterClientService.getCPtr(service));
  }

  public boolean registerKey(Sha1CheckSum key, long client_id, SWIGTYPE_p_std__string description_string) {
    return RetroshareJNI.p3GRouter_registerKey(swigCPtr, this, Sha1CheckSum.getCPtr(key), key, client_id, SWIGTYPE_p_std__string.getCPtr(description_string));
  }

  public void sendData(Sha1CheckSum destination, SWIGTYPE_p_p_void item_data, long item_size) {
    RetroshareJNI.p3GRouter_sendData(swigCPtr, this, Sha1CheckSum.getCPtr(destination), destination, SWIGTYPE_p_p_void.getCPtr(item_data), item_size);
  }

  public boolean getRoutingMatrixInfo(RoutingMatrixInfo info) {
    return RetroshareJNI.p3GRouter_getRoutingMatrixInfo(swigCPtr, this, RoutingMatrixInfo.getCPtr(info), info);
  }

  public boolean getRoutingCacheInfo(RoutingCacheInfo info) {
    return RetroshareJNI.p3GRouter_getRoutingCacheInfo(swigCPtr, this, RoutingCacheInfo.getCPtr(info), info);
  }

}
