/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class p3GxsForums extends RsGenExchange {
  private long swigCPtr;

  protected p3GxsForums(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.p3GxsForums_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(p3GxsForums obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_p3GxsForums(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public p3GxsForums(RsGeneralDataService gds, RsNetworkExchangeService nes, RsGixs gixs) {
    this(RetroshareJNI.new_p3GxsForums(RsGeneralDataService.getCPtr(gds), gds, RsNetworkExchangeService.getCPtr(nes), nes, RsGixs.getCPtr(gixs), gixs), true);
  }

  public void service_tick() {
    RetroshareJNI.p3GxsForums_service_tick(swigCPtr, this);
  }

  public boolean getGroupData(long token, SWIGTYPE_p_std__vectorT_RsGxsForumGroup_t groups) {
    return RetroshareJNI.p3GxsForums_getGroupData(swigCPtr, this, token, SWIGTYPE_p_std__vectorT_RsGxsForumGroup_t.getCPtr(groups));
  }

  public boolean getMsgData(long token, SWIGTYPE_p_std__vectorT_RsGxsForumMsg_t msgs) {
    return RetroshareJNI.p3GxsForums_getMsgData(swigCPtr, this, token, SWIGTYPE_p_std__vectorT_RsGxsForumMsg_t.getCPtr(msgs));
  }

  public boolean getRelatedMessages(long token, SWIGTYPE_p_std__vectorT_RsGxsForumMsg_t msgs) {
    return RetroshareJNI.p3GxsForums_getRelatedMessages(swigCPtr, this, token, SWIGTYPE_p_std__vectorT_RsGxsForumMsg_t.getCPtr(msgs));
  }

  public void setMessageReadStatus(SWIGTYPE_p_unsigned_int token, SWIGTYPE_p_std__pairT_std__string_std__string_t msgId, boolean read) {
    RetroshareJNI.p3GxsForums_setMessageReadStatus(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), SWIGTYPE_p_std__pairT_std__string_std__string_t.getCPtr(msgId), read);
  }

  public boolean createGroup(SWIGTYPE_p_unsigned_int token, RsGxsForumGroup group) {
    return RetroshareJNI.p3GxsForums_createGroup(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), RsGxsForumGroup.getCPtr(group), group);
  }

  public boolean createMsg(SWIGTYPE_p_unsigned_int token, RsGxsForumMsg msg) {
    return RetroshareJNI.p3GxsForums_createMsg(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), RsGxsForumMsg.getCPtr(msg), msg);
  }

}
