/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class p3NotifyPopupMsg {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected p3NotifyPopupMsg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(p3NotifyPopupMsg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_p3NotifyPopupMsg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    RetroshareJNI.p3NotifyPopupMsg_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return RetroshareJNI.p3NotifyPopupMsg_type_get(swigCPtr, this);
  }

  public void setName(SWIGTYPE_p_std__string value) {
    RetroshareJNI.p3NotifyPopupMsg_name_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getName() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.p3NotifyPopupMsg_name_get(swigCPtr, this), true);
  }

  public void setTitle(SWIGTYPE_p_std__string value) {
    RetroshareJNI.p3NotifyPopupMsg_title_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getTitle() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.p3NotifyPopupMsg_title_get(swigCPtr, this), true);
  }

  public void setMsg(SWIGTYPE_p_std__string value) {
    RetroshareJNI.p3NotifyPopupMsg_msg_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMsg() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.p3NotifyPopupMsg_msg_get(swigCPtr, this), true);
  }

  public p3NotifyPopupMsg() {
    this(RetroshareJNI.new_p3NotifyPopupMsg(), true);
  }

}
