/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class PeerNode {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PeerNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PeerNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_PeerNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PeerNode(SWIGTYPE_p_std__string id, SWIGTYPE_p_std__listT_std__string_t friends) {
    this(RetroshareJNI.new_PeerNode(SWIGTYPE_p_std__string.getCPtr(id), SWIGTYPE_p_std__listT_std__string_t.getCPtr(friends)), true);
  }

  public RsRawItem outgoing() {
    long cPtr = RetroshareJNI.PeerNode_outgoing(swigCPtr, this);
    return (cPtr == 0) ? null : new RsRawItem(cPtr, false);
  }

  public void incoming(RsRawItem arg0) {
    RetroshareJNI.PeerNode_incoming(swigCPtr, this, RsRawItem.getCPtr(arg0), arg0);
  }

  public SWIGTYPE_p_std__string id() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.PeerNode_id(swigCPtr, this), false);
  }

  public void tick() {
    RetroshareJNI.PeerNode_tick(swigCPtr, this);
  }

  public RsTurtle turtle_service() {
    long cPtr = RetroshareJNI.PeerNode_turtle_service(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTurtle(cPtr, false);
  }

  public void manageFileHash(SWIGTYPE_p_std__string hash) {
    RetroshareJNI.PeerNode_manageFileHash(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(hash));
  }

  public void provideFileHash(SWIGTYPE_p_std__string hash) {
    RetroshareJNI.PeerNode_provideFileHash(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(hash));
  }

  public SWIGTYPE_p_std__setT_std__string_t providedHashes() {
    return new SWIGTYPE_p_std__setT_std__string_t(RetroshareJNI.PeerNode_providedHashes(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__setT_std__string_t managedHashes() {
    return new SWIGTYPE_p_std__setT_std__string_t(RetroshareJNI.PeerNode_managedHashes(swigCPtr, this), false);
  }

  public void getTrafficInfo(SWIGTYPE_p_PeerNode__NodeTrafficInfo trinfo) {
    RetroshareJNI.PeerNode_getTrafficInfo(swigCPtr, this, SWIGTYPE_p_PeerNode__NodeTrafficInfo.getCPtr(trinfo));
  }

}
