/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class PeerConnectStateBox {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PeerConnectStateBox(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PeerConnectStateBox obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_PeerConnectStateBox(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PeerConnectStateBox() {
    this(RetroshareJNI.new_PeerConnectStateBox(), true);
  }

  public long connectCb(long cbtype, long netmode, long nathole, long nattype) {
    return RetroshareJNI.PeerConnectStateBox_connectCb(swigCPtr, this, cbtype, netmode, nathole, nattype);
  }

  public long updateCb(long updateType) {
    return RetroshareJNI.PeerConnectStateBox_updateCb(swigCPtr, this, updateType);
  }

  public boolean shouldUseProxyPort(long netmode, long nathole, long nattype) {
    return RetroshareJNI.PeerConnectStateBox_shouldUseProxyPort(swigCPtr, this, netmode, nathole, nattype);
  }

  public long calcNetState(long netmode, long nathole, long nattype) {
    return RetroshareJNI.PeerConnectStateBox_calcNetState(swigCPtr, this, netmode, nathole, nattype);
  }

  public SWIGTYPE_p_std__string connectState() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.PeerConnectStateBox_connectState(swigCPtr, this), true);
  }

  public void setMPeerId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.PeerConnectStateBox_mPeerId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMPeerId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.PeerConnectStateBox_mPeerId_get(swigCPtr, this), true);
  }

  public boolean storeProxyPortChoice(long flags, boolean useProxyPort) {
    return RetroshareJNI.PeerConnectStateBox_storeProxyPortChoice(swigCPtr, this, flags, useProxyPort);
  }

  public boolean getProxyPortChoice() {
    return RetroshareJNI.PeerConnectStateBox_getProxyPortChoice(swigCPtr, this);
  }

}
