/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class PeerAction {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PeerAction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PeerAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_PeerAction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMType(long value) {
    RetroshareJNI.PeerAction_mType_set(swigCPtr, this, value);
  }

  public long getMType() {
    return RetroshareJNI.PeerAction_mType_get(swigCPtr, this);
  }

  public void setMSrcId(SWIGTYPE_p_bdId value) {
    RetroshareJNI.PeerAction_mSrcId_set(swigCPtr, this, SWIGTYPE_p_bdId.getCPtr(value));
  }

  public SWIGTYPE_p_bdId getMSrcId() {
    return new SWIGTYPE_p_bdId(RetroshareJNI.PeerAction_mSrcId_get(swigCPtr, this), true);
  }

  public void setMProxyId(SWIGTYPE_p_bdId value) {
    RetroshareJNI.PeerAction_mProxyId_set(swigCPtr, this, SWIGTYPE_p_bdId.getCPtr(value));
  }

  public SWIGTYPE_p_bdId getMProxyId() {
    return new SWIGTYPE_p_bdId(RetroshareJNI.PeerAction_mProxyId_get(swigCPtr, this), true);
  }

  public void setMDestId(SWIGTYPE_p_bdId value) {
    RetroshareJNI.PeerAction_mDestId_set(swigCPtr, this, SWIGTYPE_p_bdId.getCPtr(value));
  }

  public SWIGTYPE_p_bdId getMDestId() {
    return new SWIGTYPE_p_bdId(RetroshareJNI.PeerAction_mDestId_get(swigCPtr, this), true);
  }

  public void setMMode(long value) {
    RetroshareJNI.PeerAction_mMode_set(swigCPtr, this, value);
  }

  public long getMMode() {
    return RetroshareJNI.PeerAction_mMode_get(swigCPtr, this);
  }

  public void setMPoint(long value) {
    RetroshareJNI.PeerAction_mPoint_set(swigCPtr, this, value);
  }

  public long getMPoint() {
    return RetroshareJNI.PeerAction_mPoint_get(swigCPtr, this);
  }

  public void setMAnswer(long value) {
    RetroshareJNI.PeerAction_mAnswer_set(swigCPtr, this, value);
  }

  public long getMAnswer() {
    return RetroshareJNI.PeerAction_mAnswer_get(swigCPtr, this);
  }

  public void setMDelayOrBandwidth(long value) {
    RetroshareJNI.PeerAction_mDelayOrBandwidth_set(swigCPtr, this, value);
  }

  public long getMDelayOrBandwidth() {
    return RetroshareJNI.PeerAction_mDelayOrBandwidth_get(swigCPtr, this);
  }

  public PeerAction() {
    this(RetroshareJNI.new_PeerAction(), true);
  }

}
