/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class pqiConnectCb {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pqiConnectCb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pqiConnectCb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_pqiConnectCb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void peerStatus(SWIGTYPE_p_std__string id, pqiIpAddrSet addrs, long type, long flags, long source) {
    RetroshareJNI.pqiConnectCb_peerStatus(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id), pqiIpAddrSet.getCPtr(addrs), addrs, type, flags, source);
  }

  public void peerConnectRequest(SWIGTYPE_p_std__string id, SWIGTYPE_p_sockaddr_in raddr, SWIGTYPE_p_sockaddr_in proxyaddr, SWIGTYPE_p_sockaddr_in srcaddr, long source, long flags, long delay, long bandwidth) {
    RetroshareJNI.pqiConnectCb_peerConnectRequest(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id), SWIGTYPE_p_sockaddr_in.getCPtr(raddr), SWIGTYPE_p_sockaddr_in.getCPtr(proxyaddr), SWIGTYPE_p_sockaddr_in.getCPtr(srcaddr), source, flags, delay, bandwidth);
  }

}
