/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class pqiIpAddress {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pqiIpAddress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pqiIpAddress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_pqiIpAddress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean sameAddress(pqiIpAddress a) {
    return RetroshareJNI.pqiIpAddress_sameAddress(swigCPtr, this, pqiIpAddress.getCPtr(a), a);
  }

  public boolean validAddress() {
    return RetroshareJNI.pqiIpAddress_validAddress(swigCPtr, this);
  }

  public void setMAddr(SWIGTYPE_p_sockaddr_in value) {
    RetroshareJNI.pqiIpAddress_mAddr_set(swigCPtr, this, SWIGTYPE_p_sockaddr_in.getCPtr(value));
  }

  public SWIGTYPE_p_sockaddr_in getMAddr() {
    return new SWIGTYPE_p_sockaddr_in(RetroshareJNI.pqiIpAddress_mAddr_get(swigCPtr, this), true);
  }

  public void setMSeenTime(SWIGTYPE_p_time_t value) {
    RetroshareJNI.pqiIpAddress_mSeenTime_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMSeenTime() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.pqiIpAddress_mSeenTime_get(swigCPtr, this), true);
  }

  public void setMSrc(long value) {
    RetroshareJNI.pqiIpAddress_mSrc_set(swigCPtr, this, value);
  }

  public long getMSrc() {
    return RetroshareJNI.pqiIpAddress_mSrc_get(swigCPtr, this);
  }

  public pqiIpAddress() {
    this(RetroshareJNI.new_pqiIpAddress(), true);
  }

}
