/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class pqiNetListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pqiNetListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pqiNetListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_pqiNetListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean resetListener(SWIGTYPE_p_sockaddr_in local) {
    return RetroshareJNI.pqiNetListener_resetListener(swigCPtr, this, SWIGTYPE_p_sockaddr_in.getCPtr(local));
  }

}
