/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class pqipersongrp extends pqihandler {
  private long swigCPtr;

  protected pqipersongrp(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.pqipersongrp_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pqipersongrp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_pqipersongrp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean resetListener(SWIGTYPE_p_sockaddr_in local) {
    return RetroshareJNI.pqipersongrp_resetListener(swigCPtr, this, SWIGTYPE_p_sockaddr_in.getCPtr(local));
  }

  public int init_listener() {
    return RetroshareJNI.pqipersongrp_init_listener(swigCPtr, this);
  }

  public void statusChange(SWIGTYPE_p_std__listT_pqipeer_t plist) {
    RetroshareJNI.pqipersongrp_statusChange(swigCPtr, this, SWIGTYPE_p_std__listT_pqipeer_t.getCPtr(plist));
  }

  public int addPeer(SWIGTYPE_p_std__string id) {
    return RetroshareJNI.pqipersongrp_addPeer(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id));
  }

  public int removePeer(SWIGTYPE_p_std__string id) {
    return RetroshareJNI.pqipersongrp_removePeer(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id));
  }

  public int connectPeer(SWIGTYPE_p_std__string id) {
    return RetroshareJNI.pqipersongrp_connectPeer(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id));
  }

  public int tagHeartbeatRecvd(SWIGTYPE_p_std__string id) {
    return RetroshareJNI.pqipersongrp_tagHeartbeatRecvd(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id));
  }

  public boolean notifyConnect(SWIGTYPE_p_std__string id, long type, boolean success, SWIGTYPE_p_sockaddr_in remote_peer_address) {
    return RetroshareJNI.pqipersongrp_notifyConnect(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id), type, success, SWIGTYPE_p_sockaddr_in.getCPtr(remote_peer_address));
  }

  public int tick() {
    return RetroshareJNI.pqipersongrp_tick(swigCPtr, this);
  }

  public int status() {
    return RetroshareJNI.pqipersongrp_status(swigCPtr, this);
  }

  public boolean getCryptoParams(SWIGTYPE_p_std__string arg0, RsPeerCryptoParams arg1) {
    return RetroshareJNI.pqipersongrp_getCryptoParams(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(arg0), RsPeerCryptoParams.getCPtr(arg1), arg1);
  }

}
