/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class Radix64 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Radix64(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Radix64 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_Radix64(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void decode(SWIGTYPE_p_std__string buffer, String out, SWIGTYPE_p_size_t len) {
    RetroshareJNI.Radix64_decode(SWIGTYPE_p_std__string.getCPtr(buffer), out, SWIGTYPE_p_size_t.getCPtr(len));
  }

  public static void encode(String data, int len, SWIGTYPE_p_std__string out_string) {
    RetroshareJNI.Radix64_encode(data, len, SWIGTYPE_p_std__string.getCPtr(out_string));
  }

  public Radix64() {
    this(RetroshareJNI.new_Radix64(), true);
  }

}
