/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RetroDb {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RetroDb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RetroDb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RetroDb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RetroDb(SWIGTYPE_p_std__string dbPath, int flags, SWIGTYPE_p_std__string key) {
    this(RetroshareJNI.new_RetroDb__SWIG_0(SWIGTYPE_p_std__string.getCPtr(dbPath), flags, SWIGTYPE_p_std__string.getCPtr(key)), true);
  }

  public RetroDb(SWIGTYPE_p_std__string dbPath, int flags) {
    this(RetroshareJNI.new_RetroDb__SWIG_1(SWIGTYPE_p_std__string.getCPtr(dbPath), flags), true);
  }

  public SWIGTYPE_p_std__string getKey() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RetroDb_getKey(swigCPtr, this), true);
  }

  public boolean openDb(SWIGTYPE_p_std__string dbPath, int flags) {
    return RetroshareJNI.RetroDb_openDb__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(dbPath), flags);
  }

  public boolean openDb(SWIGTYPE_p_std__string dbPath) {
    return RetroshareJNI.RetroDb_openDb__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(dbPath));
  }

  public void closeDb() {
    RetroshareJNI.RetroDb_closeDb(swigCPtr, this);
  }

  public boolean isOpen() {
    return RetroshareJNI.RetroDb_isOpen(swigCPtr, this);
  }

  public boolean execSQL(SWIGTYPE_p_std__string query) {
    return RetroshareJNI.RetroDb_execSQL(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(query));
  }

  public boolean sqlInsert(SWIGTYPE_p_std__string table, SWIGTYPE_p_std__string nullColumnHack, ContentValue cv) {
    return RetroshareJNI.RetroDb_sqlInsert(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(table), SWIGTYPE_p_std__string.getCPtr(nullColumnHack), ContentValue.getCPtr(cv), cv);
  }

  public boolean sqlUpdate(SWIGTYPE_p_std__string tableName, SWIGTYPE_p_std__string whereClause, ContentValue cv) {
    return RetroshareJNI.RetroDb_sqlUpdate(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(tableName), SWIGTYPE_p_std__string.getCPtr(whereClause), ContentValue.getCPtr(cv), cv);
  }

  public RetroCursor sqlQuery(SWIGTYPE_p_std__string tableName, SWIGTYPE_p_std__listT_std__string_t columns, SWIGTYPE_p_std__string selection, SWIGTYPE_p_std__string orderBy) {
    long cPtr = RetroshareJNI.RetroDb_sqlQuery(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(tableName), SWIGTYPE_p_std__listT_std__string_t.getCPtr(columns), SWIGTYPE_p_std__string.getCPtr(selection), SWIGTYPE_p_std__string.getCPtr(orderBy));
    return (cPtr == 0) ? null : new RetroCursor(cPtr, false);
  }

  public boolean sqlDelete(SWIGTYPE_p_std__string tableName, SWIGTYPE_p_std__string whereClause, SWIGTYPE_p_std__string whereArgs) {
    return RetroshareJNI.RetroDb_sqlDelete(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(tableName), SWIGTYPE_p_std__string.getCPtr(whereClause), SWIGTYPE_p_std__string.getCPtr(whereArgs));
  }

  public void vacuum() {
    RetroshareJNI.RetroDb_vacuum(swigCPtr, this);
  }

  public void buildInsertQueryValue(SWIGTYPE_p_std__mapT_std__string_unsigned_char_t keyMap, ContentValue cv, SWIGTYPE_p_std__string parameter, SWIGTYPE_p_std__listT_RetroBind_p_t paramBindings) {
    RetroshareJNI.RetroDb_buildInsertQueryValue(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_unsigned_char_t.getCPtr(keyMap), ContentValue.getCPtr(cv), cv, SWIGTYPE_p_std__string.getCPtr(parameter), SWIGTYPE_p_std__listT_RetroBind_p_t.getCPtr(paramBindings));
  }

  public void buildUpdateQueryValue(SWIGTYPE_p_std__mapT_std__string_unsigned_char_t keyMap, ContentValue cv, SWIGTYPE_p_std__string parameter, SWIGTYPE_p_std__listT_RetroBind_p_t paramBindings) {
    RetroshareJNI.RetroDb_buildUpdateQueryValue(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_unsigned_char_t.getCPtr(keyMap), ContentValue.getCPtr(cv), cv, SWIGTYPE_p_std__string.getCPtr(parameter), SWIGTYPE_p_std__listT_RetroBind_p_t.getCPtr(paramBindings));
  }

  public static int getOPEN_READONLY() {
    return RetroshareJNI.RetroDb_OPEN_READONLY_get();
  }

  public static int getOPEN_READWRITE() {
    return RetroshareJNI.RetroDb_OPEN_READWRITE_get();
  }

  public static int getOPEN_READWRITE_CREATE() {
    return RetroshareJNI.RetroDb_OPEN_READWRITE_CREATE_get();
  }

}
