/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsChatAvatarItem extends RsChatItem {
  private long swigCPtr;

  protected RsChatAvatarItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsChatAvatarItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsChatAvatarItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsChatAvatarItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsChatAvatarItem() {
    this(RetroshareJNI.new_RsChatAvatarItem__SWIG_0(), true);
  }

  public RsChatAvatarItem(SWIGTYPE_p_void data, long size) {
    this(RetroshareJNI.new_RsChatAvatarItem__SWIG_1(SWIGTYPE_p_void.getCPtr(data), size), true);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsChatAvatarItem_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsChatAvatarItem_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public boolean serialise(SWIGTYPE_p_void data, SWIGTYPE_p_unsigned_int size) {
    return RetroshareJNI.RsChatAvatarItem_serialise(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_unsigned_int.getCPtr(size));
  }

  public long serial_size() {
    return RetroshareJNI.RsChatAvatarItem_serial_size(swigCPtr, this);
  }

  public void setImage_size(long value) {
    RetroshareJNI.RsChatAvatarItem_image_size_set(swigCPtr, this, value);
  }

  public long getImage_size() {
    return RetroshareJNI.RsChatAvatarItem_image_size_get(swigCPtr, this);
  }

  public void setImage_data(SWIGTYPE_p_unsigned_char value) {
    RetroshareJNI.RsChatAvatarItem_image_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getImage_data() {
    long cPtr = RetroshareJNI.RsChatAvatarItem_image_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

}
