/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsControl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RsControl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsControl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsControl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int StartupRetroShare() {
    return RetroshareJNI.RsControl_StartupRetroShare(swigCPtr, this);
  }

  public int SetInBroadcast(SWIGTYPE_p_std__string id, boolean in) {
    return RetroshareJNI.RsControl_SetInBroadcast(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id), in);
  }

  public int SetInSubscribe(SWIGTYPE_p_std__string id, boolean in) {
    return RetroshareJNI.RsControl_SetInSubscribe(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id), in);
  }

  public int ClearInBroadcast() {
    return RetroshareJNI.RsControl_ClearInBroadcast(swigCPtr, this);
  }

  public int ClearInSubscribe() {
    return RetroshareJNI.RsControl_ClearInSubscribe(swigCPtr, this);
  }

  public int ConfigSetBootPrompt(boolean on) {
    return RetroshareJNI.RsControl_ConfigSetBootPrompt(swigCPtr, this, on);
  }

  public void ConfigFinalSave() {
    RetroshareJNI.RsControl_ConfigFinalSave(swigCPtr, this);
  }

  public void rsGlobalShutDown() {
    RetroshareJNI.RsControl_rsGlobalShutDown(swigCPtr, this);
  }

  public NotifyBase getNotify() {
    return new NotifyBase(RetroshareJNI.RsControl_getNotify(swigCPtr, this), false);
  }

  public boolean getPeerCryptoDetails(SWIGTYPE_p_std__string ssl_id, RsPeerCryptoParams params) {
    return RetroshareJNI.RsControl_getPeerCryptoDetails(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(ssl_id), RsPeerCryptoParams.getCPtr(params), params);
  }

}
