/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsDataService extends RsGeneralDataService {
  private long swigCPtr;

  protected RsDataService(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsDataService_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsDataService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsDataService(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsDataService(SWIGTYPE_p_std__string serviceDir, SWIGTYPE_p_std__string dbName, int serviceType, RsGxsSearchModule mod, SWIGTYPE_p_std__string key) {
    this(RetroshareJNI.new_RsDataService__SWIG_0(SWIGTYPE_p_std__string.getCPtr(serviceDir), SWIGTYPE_p_std__string.getCPtr(dbName), serviceType, RsGxsSearchModule.getCPtr(mod), mod, SWIGTYPE_p_std__string.getCPtr(key)), true);
  }

  public RsDataService(SWIGTYPE_p_std__string serviceDir, SWIGTYPE_p_std__string dbName, int serviceType, RsGxsSearchModule mod) {
    this(RetroshareJNI.new_RsDataService__SWIG_1(SWIGTYPE_p_std__string.getCPtr(serviceDir), SWIGTYPE_p_std__string.getCPtr(dbName), serviceType, RsGxsSearchModule.getCPtr(mod), mod), true);
  }

  public RsDataService(SWIGTYPE_p_std__string serviceDir, SWIGTYPE_p_std__string dbName, int serviceType) {
    this(RetroshareJNI.new_RsDataService__SWIG_2(SWIGTYPE_p_std__string.getCPtr(serviceDir), SWIGTYPE_p_std__string.getCPtr(dbName), serviceType), true);
  }

  public int retrieveNxsMsgs(SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t reqIds, SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsNxsMsg_p_t_t msg, boolean cache, boolean withMeta) {
    return RetroshareJNI.RsDataService_retrieveNxsMsgs__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t.getCPtr(reqIds), SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsNxsMsg_p_t_t.getCPtr(msg), cache, withMeta);
  }

  public int retrieveNxsMsgs(SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t reqIds, SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsNxsMsg_p_t_t msg, boolean cache) {
    return RetroshareJNI.RsDataService_retrieveNxsMsgs__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t.getCPtr(reqIds), SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsNxsMsg_p_t_t.getCPtr(msg), cache);
  }

  public int retrieveNxsGrps(SWIGTYPE_p_std__mapT_std__string_RsNxsGrp_p_t grp, boolean withMeta, boolean cache) {
    return RetroshareJNI.RsDataService_retrieveNxsGrps(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_RsNxsGrp_p_t.getCPtr(grp), withMeta, cache);
  }

  public int retrieveGxsGrpMetaData(SWIGTYPE_p_std__mapT_std__string_RsGxsGrpMetaData_p_t grp) {
    return RetroshareJNI.RsDataService_retrieveGxsGrpMetaData(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_RsGxsGrpMetaData_p_t.getCPtr(grp));
  }

  public int retrieveGxsMsgMetaData(SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t reqIds, SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsGxsMsgMetaData_p_t_t msgMeta) {
    return RetroshareJNI.RsDataService_retrieveGxsMsgMetaData(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t.getCPtr(reqIds), SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsGxsMsgMetaData_p_t_t.getCPtr(msgMeta));
  }

  public int removeMsgs(SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t msgIds) {
    return RetroshareJNI.RsDataService_removeMsgs(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t.getCPtr(msgIds));
  }

  public int removeGroups(SWIGTYPE_p_std__vectorT_std__string_t grpIds) {
    return RetroshareJNI.RsDataService_removeGroups(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(grpIds));
  }

  public long cacheSize() {
    return RetroshareJNI.RsDataService_cacheSize(swigCPtr, this);
  }

  public int setCacheSize(long size) {
    return RetroshareJNI.RsDataService_setCacheSize(swigCPtr, this, size);
  }

  public int storeMessage(SWIGTYPE_p_std__mapT_RsNxsMsg_p_RsGxsMsgMetaData_p_t msg) {
    return RetroshareJNI.RsDataService_storeMessage(swigCPtr, this, SWIGTYPE_p_std__mapT_RsNxsMsg_p_RsGxsMsgMetaData_p_t.getCPtr(msg));
  }

  public int storeGroup(SWIGTYPE_p_std__mapT_RsNxsGrp_p_RsGxsGrpMetaData_p_t grp) {
    return RetroshareJNI.RsDataService_storeGroup(swigCPtr, this, SWIGTYPE_p_std__mapT_RsNxsGrp_p_RsGxsGrpMetaData_p_t.getCPtr(grp));
  }

  public int updateMessageMetaData(MsgLocMetaData metaData) {
    return RetroshareJNI.RsDataService_updateMessageMetaData(swigCPtr, this, MsgLocMetaData.getCPtr(metaData), metaData);
  }

  public int updateGroupMetaData(GrpLocMetaData meta) {
    return RetroshareJNI.RsDataService_updateGroupMetaData(swigCPtr, this, GrpLocMetaData.getCPtr(meta), meta);
  }

  public int resetDataStore() {
    return RetroshareJNI.RsDataService_resetDataStore(swigCPtr, this);
  }

  public boolean validSize(RsNxsMsg msg) {
    return RetroshareJNI.RsDataService_validSize__SWIG_0(swigCPtr, this, RsNxsMsg.getCPtr(msg), msg);
  }

  public boolean validSize(RsNxsGrp grp) {
    return RetroshareJNI.RsDataService_validSize__SWIG_1(swigCPtr, this, RsNxsGrp.getCPtr(grp), grp);
  }

}
