/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsDistribGrp extends RsItem {
  private long swigCPtr;

  protected RsDistribGrp(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsDistribGrp_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsDistribGrp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsDistribGrp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsDistribGrp() {
    this(RetroshareJNI.new_RsDistribGrp(), true);
  }

  public void clear() {
    RetroshareJNI.RsDistribGrp_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsDistribGrp_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsDistribGrp_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public void setGrpId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsDistribGrp_grpId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getGrpId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsDistribGrp_grpId_get(swigCPtr, this), true);
  }

  public void setTimestamp(long value) {
    RetroshareJNI.RsDistribGrp_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return RetroshareJNI.RsDistribGrp_timestamp_get(swigCPtr, this);
  }

  public void setGrpFlags(long value) {
    RetroshareJNI.RsDistribGrp_grpFlags_set(swigCPtr, this, value);
  }

  public long getGrpFlags() {
    return RetroshareJNI.RsDistribGrp_grpFlags_get(swigCPtr, this);
  }

  public void setGrpName(SWIGTYPE_p_std__wstring value) {
    RetroshareJNI.RsDistribGrp_grpName_set(swigCPtr, this, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getGrpName() {
    return new SWIGTYPE_p_std__wstring(RetroshareJNI.RsDistribGrp_grpName_get(swigCPtr, this), true);
  }

  public void setGrpDesc(SWIGTYPE_p_std__wstring value) {
    RetroshareJNI.RsDistribGrp_grpDesc_set(swigCPtr, this, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getGrpDesc() {
    return new SWIGTYPE_p_std__wstring(RetroshareJNI.RsDistribGrp_grpDesc_get(swigCPtr, this), true);
  }

  public void setGrpCategory(SWIGTYPE_p_std__wstring value) {
    RetroshareJNI.RsDistribGrp_grpCategory_set(swigCPtr, this, SWIGTYPE_p_std__wstring.getCPtr(value));
  }

  public SWIGTYPE_p_std__wstring getGrpCategory() {
    return new SWIGTYPE_p_std__wstring(RetroshareJNI.RsDistribGrp_grpCategory_get(swigCPtr, this), true);
  }

  public void setGrpPixmap(RsTlvImage value) {
    RetroshareJNI.RsDistribGrp_grpPixmap_set(swigCPtr, this, RsTlvImage.getCPtr(value), value);
  }

  public RsTlvImage getGrpPixmap() {
    long cPtr = RetroshareJNI.RsDistribGrp_grpPixmap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvImage(cPtr, false);
  }

  public void setGrpControlFlags(long value) {
    RetroshareJNI.RsDistribGrp_grpControlFlags_set(swigCPtr, this, value);
  }

  public long getGrpControlFlags() {
    return RetroshareJNI.RsDistribGrp_grpControlFlags_get(swigCPtr, this);
  }

  public void setGrpControlList(RsTlvPeerIdSet value) {
    RetroshareJNI.RsDistribGrp_grpControlList_set(swigCPtr, this, RsTlvPeerIdSet.getCPtr(value), value);
  }

  public RsTlvPeerIdSet getGrpControlList() {
    long cPtr = RetroshareJNI.RsDistribGrp_grpControlList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvPeerIdSet(cPtr, false);
  }

  public void setAdminKey(RsTlvSecurityKey value) {
    RetroshareJNI.RsDistribGrp_adminKey_set(swigCPtr, this, RsTlvSecurityKey.getCPtr(value), value);
  }

  public RsTlvSecurityKey getAdminKey() {
    long cPtr = RetroshareJNI.RsDistribGrp_adminKey_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvSecurityKey(cPtr, false);
  }

  public void setPublishKeys(RsTlvSecurityKeySet value) {
    RetroshareJNI.RsDistribGrp_publishKeys_set(swigCPtr, this, RsTlvSecurityKeySet.getCPtr(value), value);
  }

  public RsTlvSecurityKeySet getPublishKeys() {
    long cPtr = RetroshareJNI.RsDistribGrp_publishKeys_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvSecurityKeySet(cPtr, false);
  }

  public void setAdminSignature(RsTlvKeySignature value) {
    RetroshareJNI.RsDistribGrp_adminSignature_set(swigCPtr, this, RsTlvKeySignature.getCPtr(value), value);
  }

  public RsTlvKeySignature getAdminSignature() {
    long cPtr = RetroshareJNI.RsDistribGrp_adminSignature_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvKeySignature(cPtr, false);
  }

}
