/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsFeedItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RsFeedItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsFeedItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsFeedItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RsFeedItem(long type, SWIGTYPE_p_std__string id1, SWIGTYPE_p_std__string id2, SWIGTYPE_p_std__string id3) {
    this(RetroshareJNI.new_RsFeedItem__SWIG_0(type, SWIGTYPE_p_std__string.getCPtr(id1), SWIGTYPE_p_std__string.getCPtr(id2), SWIGTYPE_p_std__string.getCPtr(id3)), true);
  }

  public RsFeedItem(long type, SWIGTYPE_p_std__string id1, SWIGTYPE_p_std__string id2, SWIGTYPE_p_std__string id3, SWIGTYPE_p_std__string id4) {
    this(RetroshareJNI.new_RsFeedItem__SWIG_1(type, SWIGTYPE_p_std__string.getCPtr(id1), SWIGTYPE_p_std__string.getCPtr(id2), SWIGTYPE_p_std__string.getCPtr(id3), SWIGTYPE_p_std__string.getCPtr(id4)), true);
  }

  public RsFeedItem() {
    this(RetroshareJNI.new_RsFeedItem__SWIG_2(), true);
  }

  public void setMType(long value) {
    RetroshareJNI.RsFeedItem_mType_set(swigCPtr, this, value);
  }

  public long getMType() {
    return RetroshareJNI.RsFeedItem_mType_get(swigCPtr, this);
  }

  public void setMId1(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsFeedItem_mId1_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMId1() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsFeedItem_mId1_get(swigCPtr, this), true);
  }

  public void setMId2(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsFeedItem_mId2_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMId2() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsFeedItem_mId2_get(swigCPtr, this), true);
  }

  public void setMId3(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsFeedItem_mId3_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMId3() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsFeedItem_mId3_get(swigCPtr, this), true);
  }

  public void setMId4(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsFeedItem_mId4_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMId4() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsFeedItem_mId4_get(swigCPtr, this), true);
  }

}
