/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsFileChunkMap extends RsItem {
  private long swigCPtr;

  protected RsFileChunkMap(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsFileChunkMap_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsFileChunkMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsFileChunkMap(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsFileChunkMap() {
    this(RetroshareJNI.new_RsFileChunkMap(), true);
  }

  public void clear() {
    RetroshareJNI.RsFileChunkMap_clear(swigCPtr, this);
  }

  public void setIs_client(boolean value) {
    RetroshareJNI.RsFileChunkMap_is_client_set(swigCPtr, this, value);
  }

  public boolean getIs_client() {
    return RetroshareJNI.RsFileChunkMap_is_client_get(swigCPtr, this);
  }

  public void setHash(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsFileChunkMap_hash_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getHash() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsFileChunkMap_hash_get(swigCPtr, this), true);
  }

  public void setCompressed_map(CompressedChunkMap value) {
    RetroshareJNI.RsFileChunkMap_compressed_map_set(swigCPtr, this, CompressedChunkMap.getCPtr(value), value);
  }

  public CompressedChunkMap getCompressed_map() {
    long cPtr = RetroshareJNI.RsFileChunkMap_compressed_map_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CompressedChunkMap(cPtr, false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsFileChunkMap_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsFileChunkMap_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

}
