/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsFileRequest extends RsItem {
  private long swigCPtr;

  protected RsFileRequest(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsFileRequest_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsFileRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsFileRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsFileRequest() {
    this(RetroshareJNI.new_RsFileRequest(), true);
  }

  public void clear() {
    RetroshareJNI.RsFileRequest_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsFileRequest_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsFileRequest_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public void setFileoffset(java.math.BigInteger value) {
    RetroshareJNI.RsFileRequest_fileoffset_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getFileoffset() {
    return RetroshareJNI.RsFileRequest_fileoffset_get(swigCPtr, this);
  }

  public void setChunksize(long value) {
    RetroshareJNI.RsFileRequest_chunksize_set(swigCPtr, this, value);
  }

  public long getChunksize() {
    return RetroshareJNI.RsFileRequest_chunksize_get(swigCPtr, this);
  }

  public void setFile(RsTlvFileItem value) {
    RetroshareJNI.RsFileRequest_file_set(swigCPtr, this, RsTlvFileItem.getCPtr(value), value);
  }

  public RsTlvFileItem getFile() {
    long cPtr = RetroshareJNI.RsFileRequest_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvFileItem(cPtr, false);
  }

}
