/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsGRouterACKItem extends RsGRouterItem {
  private long swigCPtr;

  protected RsGRouterACKItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsGRouterACKItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsGRouterACKItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsGRouterACKItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsGRouterACKItem() {
    this(RetroshareJNI.new_RsGRouterACKItem(), true);
  }

  public boolean serialise(SWIGTYPE_p_void data, SWIGTYPE_p_unsigned_int size) {
    return RetroshareJNI.RsGRouterACKItem_serialise(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_unsigned_int.getCPtr(size));
  }

  public long serial_size() {
    return RetroshareJNI.RsGRouterACKItem_serial_size(swigCPtr, this);
  }

  public void clear() {
    RetroshareJNI.RsGRouterACKItem_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGRouterACKItem_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGRouterACKItem_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public void setDestination_key(Sha1CheckSum value) {
    RetroshareJNI.RsGRouterACKItem_destination_key_set(swigCPtr, this, Sha1CheckSum.getCPtr(value), value);
  }

  public Sha1CheckSum getDestination_key() {
    long cPtr = RetroshareJNI.RsGRouterACKItem_destination_key_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Sha1CheckSum(cPtr, false);
  }

  public void setState(long value) {
    RetroshareJNI.RsGRouterACKItem_state_set(swigCPtr, this, value);
  }

  public long getState() {
    return RetroshareJNI.RsGRouterACKItem_state_get(swigCPtr, this);
  }

}
