/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsGRouter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RsGRouter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsGRouter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsGRouter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getRoutingCacheInfo(RoutingCacheInfo info) {
    return RetroshareJNI.RsGRouter_getRoutingCacheInfo(swigCPtr, this, RoutingCacheInfo.getCPtr(info), info);
  }

  public boolean getRoutingMatrixInfo(RoutingMatrixInfo info) {
    return RetroshareJNI.RsGRouter_getRoutingMatrixInfo(swigCPtr, this, RoutingMatrixInfo.getCPtr(info), info);
  }

  public void sendData(Sha1CheckSum destination, SWIGTYPE_p_p_void item_data, long item_size) {
    RetroshareJNI.RsGRouter_sendData(swigCPtr, this, Sha1CheckSum.getCPtr(destination), destination, SWIGTYPE_p_p_void.getCPtr(item_data), item_size);
  }

  public boolean registerKey(Sha1CheckSum key, long client_id, SWIGTYPE_p_std__string description_string) {
    return RetroshareJNI.RsGRouter_registerKey(swigCPtr, this, Sha1CheckSum.getCPtr(key), key, client_id, SWIGTYPE_p_std__string.getCPtr(description_string));
  }

}
