/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsGxsWikiSnapshotItem extends RsGxsMsgItem {
  private long swigCPtr;

  protected RsGxsWikiSnapshotItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsGxsWikiSnapshotItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsGxsWikiSnapshotItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsGxsWikiSnapshotItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsGxsWikiSnapshotItem() {
    this(RetroshareJNI.new_RsGxsWikiSnapshotItem(), true);
  }

  public void clear() {
    RetroshareJNI.RsGxsWikiSnapshotItem_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGxsWikiSnapshotItem_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGxsWikiSnapshotItem_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public void setSnapshot(RsWikiSnapshot value) {
    RetroshareJNI.RsGxsWikiSnapshotItem_snapshot_set(swigCPtr, this, RsWikiSnapshot.getCPtr(value), value);
  }

  public RsWikiSnapshot getSnapshot() {
    long cPtr = RetroshareJNI.RsGxsWikiSnapshotItem_snapshot_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsWikiSnapshot(cPtr, false);
  }

}
