/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsGxsCommentService {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RsGxsCommentService(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsGxsCommentService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsGxsCommentService(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getCommentData(long token, SWIGTYPE_p_std__vectorT_RsGxsComment_t comments) {
    return RetroshareJNI.RsGxsCommentService_getCommentData(swigCPtr, this, token, SWIGTYPE_p_std__vectorT_RsGxsComment_t.getCPtr(comments));
  }

  public boolean getRelatedComments(long token, SWIGTYPE_p_std__vectorT_RsGxsComment_t comments) {
    return RetroshareJNI.RsGxsCommentService_getRelatedComments(swigCPtr, this, token, SWIGTYPE_p_std__vectorT_RsGxsComment_t.getCPtr(comments));
  }

  public boolean createComment(SWIGTYPE_p_unsigned_int token, RsGxsComment comment) {
    return RetroshareJNI.RsGxsCommentService_createComment(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), RsGxsComment.getCPtr(comment), comment);
  }

  public boolean createVote(SWIGTYPE_p_unsigned_int token, RsGxsVote vote) {
    return RetroshareJNI.RsGxsCommentService_createVote(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), RsGxsVote.getCPtr(vote), vote);
  }

  public boolean acknowledgeComment(long token, SWIGTYPE_p_std__pairT_std__string_std__string_t msgId) {
    return RetroshareJNI.RsGxsCommentService_acknowledgeComment(swigCPtr, this, token, SWIGTYPE_p_std__pairT_std__string_std__string_t.getCPtr(msgId));
  }

  public boolean acknowledgeVote(long token, SWIGTYPE_p_std__pairT_std__string_std__string_t msgId) {
    return RetroshareJNI.RsGxsCommentService_acknowledgeVote(swigCPtr, this, token, SWIGTYPE_p_std__pairT_std__string_std__string_t.getCPtr(msgId));
  }

}
