/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsGxsGroupChange extends RsGxsNotify {
  private long swigCPtr;

  protected RsGxsGroupChange(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsGxsGroupChange_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsGxsGroupChange obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsGxsGroupChange(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsGxsGroupChange(RsGxsNotify.NotifyType type) {
    this(RetroshareJNI.new_RsGxsGroupChange(type.swigValue()), true);
  }

  public void setMGrpIdList(SWIGTYPE_p_std__listT_std__string_t value) {
    RetroshareJNI.RsGxsGroupChange_mGrpIdList_set(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_std__string_t getMGrpIdList() {
    return new SWIGTYPE_p_std__listT_std__string_t(RetroshareJNI.RsGxsGroupChange_mGrpIdList_get(swigCPtr, this), true);
  }

  public RsGxsNotify.NotifyType getType() {
    return RsGxsNotify.NotifyType.swigToEnum(RetroshareJNI.RsGxsGroupChange_getType(swigCPtr, this));
  }

}
