/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsGxsPhotoAlbumItem extends RsGxsGrpItem {
  private long swigCPtr;

  protected RsGxsPhotoAlbumItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsGxsPhotoAlbumItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsGxsPhotoAlbumItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsGxsPhotoAlbumItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsGxsPhotoAlbumItem() {
    this(RetroshareJNI.new_RsGxsPhotoAlbumItem(), true);
  }

  public void clear() {
    RetroshareJNI.RsGxsPhotoAlbumItem_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGxsPhotoAlbumItem_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGxsPhotoAlbumItem_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public void setAlbum(RsPhotoAlbum value) {
    RetroshareJNI.RsGxsPhotoAlbumItem_album_set(swigCPtr, this, RsPhotoAlbum.getCPtr(value), value);
  }

  public RsPhotoAlbum getAlbum() {
    long cPtr = RetroshareJNI.RsGxsPhotoAlbumItem_album_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsPhotoAlbum(cPtr, false);
  }

}
