/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsGxsWireGroupItem extends RsGxsGrpItem {
  private long swigCPtr;

  protected RsGxsWireGroupItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsGxsWireGroupItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsGxsWireGroupItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsGxsWireGroupItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsGxsWireGroupItem() {
    this(RetroshareJNI.new_RsGxsWireGroupItem(), true);
  }

  public void clear() {
    RetroshareJNI.RsGxsWireGroupItem_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGxsWireGroupItem_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGxsWireGroupItem_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public void setGroup(RsWireGroup value) {
    RetroshareJNI.RsGxsWireGroupItem_group_set(swigCPtr, this, RsWireGroup.getCPtr(value), value);
  }

  public RsWireGroup getGroup() {
    long cPtr = RetroshareJNI.RsGxsWireGroupItem_group_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsWireGroup(cPtr, false);
  }

}
