/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsGxsChannelGroupItem extends RsGxsGrpItem {
  private long swigCPtr;

  protected RsGxsChannelGroupItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsGxsChannelGroupItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsGxsChannelGroupItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsGxsChannelGroupItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsGxsChannelGroupItem() {
    this(RetroshareJNI.new_RsGxsChannelGroupItem(), true);
  }

  public void clear() {
    RetroshareJNI.RsGxsChannelGroupItem_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGxsChannelGroupItem_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsGxsChannelGroupItem_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public boolean fromChannelGroup(RsGxsChannelGroup group, boolean moveImage) {
    return RetroshareJNI.RsGxsChannelGroupItem_fromChannelGroup(swigCPtr, this, RsGxsChannelGroup.getCPtr(group), group, moveImage);
  }

  public boolean toChannelGroup(RsGxsChannelGroup group, boolean moveImage) {
    return RetroshareJNI.RsGxsChannelGroupItem_toChannelGroup(swigCPtr, this, RsGxsChannelGroup.getCPtr(group), group, moveImage);
  }

  public void setMDescription(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsGxsChannelGroupItem_mDescription_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMDescription() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsGxsChannelGroupItem_mDescription_get(swigCPtr, this), true);
  }

  public void setMImage(RsTlvImage value) {
    RetroshareJNI.RsGxsChannelGroupItem_mImage_set(swigCPtr, this, RsTlvImage.getCPtr(value), value);
  }

  public RsTlvImage getMImage() {
    long cPtr = RetroshareJNI.RsGxsChannelGroupItem_mImage_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvImage(cPtr, false);
  }

}
