/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsHistory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RsHistory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsHistory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsHistory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getMessages(SWIGTYPE_p_std__string chatPeerId, SWIGTYPE_p_std__listT_HistoryMsg_t msgs, long loadCount) {
    return RetroshareJNI.RsHistory_getMessages(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(chatPeerId), SWIGTYPE_p_std__listT_HistoryMsg_t.getCPtr(msgs), loadCount);
  }

  public boolean getMessage(long msgId, HistoryMsg msg) {
    return RetroshareJNI.RsHistory_getMessage(swigCPtr, this, msgId, HistoryMsg.getCPtr(msg), msg);
  }

  public void removeMessages(SWIGTYPE_p_std__listT_unsigned_int_t msgIds) {
    RetroshareJNI.RsHistory_removeMessages(swigCPtr, this, SWIGTYPE_p_std__listT_unsigned_int_t.getCPtr(msgIds));
  }

  public void clear(SWIGTYPE_p_std__string chatPeerId) {
    RetroshareJNI.RsHistory_clear(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(chatPeerId));
  }

  public boolean getEnable(long chat_type) {
    return RetroshareJNI.RsHistory_getEnable(swigCPtr, this, chat_type);
  }

  public void setEnable(long chat_type, boolean enable) {
    RetroshareJNI.RsHistory_setEnable(swigCPtr, this, chat_type, enable);
  }

  public long getMaxStorageDuration() {
    return RetroshareJNI.RsHistory_getMaxStorageDuration(swigCPtr, this);
  }

  public void setMaxStorageDuration(long seconds) {
    RetroshareJNI.RsHistory_setMaxStorageDuration(swigCPtr, this, seconds);
  }

  public long getSaveCount(long chat_type) {
    return RetroshareJNI.RsHistory_getSaveCount(swigCPtr, this, chat_type);
  }

  public void setSaveCount(long chat_type, long count) {
    RetroshareJNI.RsHistory_setSaveCount(swigCPtr, this, chat_type, count);
  }

}
