/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsMsgSrcId extends RsMessageItem {
  private long swigCPtr;

  protected RsMsgSrcId(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsMsgSrcId_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsMsgSrcId obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsMsgSrcId(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsMsgSrcId() {
    this(RetroshareJNI.new_RsMsgSrcId(), true);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsMsgSrcId_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsMsgSrcId_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public boolean serialise(SWIGTYPE_p_void data, SWIGTYPE_p_unsigned_int size, boolean config) {
    return RetroshareJNI.RsMsgSrcId_serialise(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_unsigned_int.getCPtr(size), config);
  }

  public long serial_size(boolean config) {
    return RetroshareJNI.RsMsgSrcId_serial_size(swigCPtr, this, config);
  }

  public void clear() {
    RetroshareJNI.RsMsgSrcId_clear(swigCPtr, this);
  }

  public void setMsgId(long value) {
    RetroshareJNI.RsMsgSrcId_msgId_set(swigCPtr, this, value);
  }

  public long getMsgId() {
    return RetroshareJNI.RsMsgSrcId_msgId_get(swigCPtr, this);
  }

  public void setSrcId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsMsgSrcId_srcId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getSrcId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsMsgSrcId_srcId_get(swigCPtr, this), true);
  }

}
