/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsNxsDeleteMsg {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RsNxsDeleteMsg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsNxsDeleteMsg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsNxsDeleteMsg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RsNxsDeleteMsg() {
    this(RetroshareJNI.new_RsNxsDeleteMsg(), true);
  }

  public void setMsgId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsNxsDeleteMsg_msgId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getMsgId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsNxsDeleteMsg_msgId_get(swigCPtr, this), true);
  }

  public void setGrpId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsNxsDeleteMsg_grpId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getGrpId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsNxsDeleteMsg_grpId_get(swigCPtr, this), true);
  }

  public void setDeleteSign(RsTlvKeySignature value) {
    RetroshareJNI.RsNxsDeleteMsg_deleteSign_set(swigCPtr, this, RsTlvKeySignature.getCPtr(value), value);
  }

  public RsTlvKeySignature getDeleteSign() {
    long cPtr = RetroshareJNI.RsNxsDeleteMsg_deleteSign_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvKeySignature(cPtr, false);
  }

}
