/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsPeerServicePermissionItem extends RsItem {
  private long swigCPtr;

  protected RsPeerServicePermissionItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsPeerServicePermissionItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsPeerServicePermissionItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsPeerServicePermissionItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsPeerServicePermissionItem() {
    this(RetroshareJNI.new_RsPeerServicePermissionItem(), true);
  }

  public void clear() {
    RetroshareJNI.RsPeerServicePermissionItem_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsPeerServicePermissionItem_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsPeerServicePermissionItem_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out)), false);
  }

  public void setPgp_ids(SWIGTYPE_p_std__vectorT_std__string_t value) {
    RetroshareJNI.RsPeerServicePermissionItem_pgp_ids_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getPgp_ids() {
    return new SWIGTYPE_p_std__vectorT_std__string_t(RetroshareJNI.RsPeerServicePermissionItem_pgp_ids_get(swigCPtr, this), true);
  }

  public void setService_flags(SWIGTYPE_p_std__vectorT_t_RsFlags32T_0x380912_t_t value) {
    RetroshareJNI.RsPeerServicePermissionItem_service_flags_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_t_RsFlags32T_0x380912_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_t_RsFlags32T_0x380912_t_t getService_flags() {
    return new SWIGTYPE_p_std__vectorT_t_RsFlags32T_0x380912_t_t(RetroshareJNI.RsPeerServicePermissionItem_service_flags_get(swigCPtr, this), true);
  }

}
