/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsPhoto {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RsPhoto(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsPhoto obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsPhoto(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static long getFLAG_MSG_TYPE_PHOTO_POST() {
    return RetroshareJNI.RsPhoto_FLAG_MSG_TYPE_PHOTO_POST_get();
  }

  public static long getFLAG_MSG_TYPE_PHOTO_COMMENT() {
    return RetroshareJNI.RsPhoto_FLAG_MSG_TYPE_PHOTO_COMMENT_get();
  }

  public static long getFLAG_MSG_TYPE_MASK() {
    return RetroshareJNI.RsPhoto_FLAG_MSG_TYPE_MASK_get();
  }

  public boolean updated() {
    return RetroshareJNI.RsPhoto_updated(swigCPtr, this);
  }

  public void groupsChanged(SWIGTYPE_p_std__listT_std__string_t grpIds) {
    RetroshareJNI.RsPhoto_groupsChanged(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(grpIds));
  }

  public void msgsChanged(SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t msgs) {
    RetroshareJNI.RsPhoto_msgsChanged(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t.getCPtr(msgs));
  }

  public RsTokenService getTokenService() {
    long cPtr = RetroshareJNI.RsPhoto_getTokenService(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTokenService(cPtr, false);
  }

  public boolean getGroupList(long token, SWIGTYPE_p_std__listT_std__string_t groupIds) {
    return RetroshareJNI.RsPhoto_getGroupList(swigCPtr, this, token, SWIGTYPE_p_std__listT_std__string_t.getCPtr(groupIds));
  }

  public boolean getMsgList(long token, SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t msgIds) {
    return RetroshareJNI.RsPhoto_getMsgList(swigCPtr, this, token, SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t.getCPtr(msgIds));
  }

  public boolean getGroupSummary(long token, SWIGTYPE_p_std__listT_RsGroupMetaData_t groupInfo) {
    return RetroshareJNI.RsPhoto_getGroupSummary(swigCPtr, this, token, SWIGTYPE_p_std__listT_RsGroupMetaData_t.getCPtr(groupInfo));
  }

  public boolean getMsgSummary(long token, SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsMsgMetaData_t_t msgInfo) {
    return RetroshareJNI.RsPhoto_getMsgSummary(swigCPtr, this, token, SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsMsgMetaData_t_t.getCPtr(msgInfo));
  }

  public boolean getAlbum(long token, SWIGTYPE_p_std__vectorT_RsPhotoAlbum_t album) {
    return RetroshareJNI.RsPhoto_getAlbum(swigCPtr, this, token, SWIGTYPE_p_std__vectorT_RsPhotoAlbum_t.getCPtr(album));
  }

  public boolean getPhoto(long token, SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsPhotoPhoto_t_t photo) {
    return RetroshareJNI.RsPhoto_getPhoto(swigCPtr, this, token, SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsPhotoPhoto_t_t.getCPtr(photo));
  }

  public boolean getPhotoComment(long token, SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsPhotoComment_t_t comments) {
    return RetroshareJNI.RsPhoto_getPhotoComment(swigCPtr, this, token, SWIGTYPE_p_std__mapT_std__string_std__vectorT_RsPhotoComment_t_t.getCPtr(comments));
  }

  public boolean getPhotoRelatedComment(long token, SWIGTYPE_p_std__mapT_std__pairT_std__string_std__string_t_std__vectorT_RsPhotoComment_t_t comments) {
    return RetroshareJNI.RsPhoto_getPhotoRelatedComment(swigCPtr, this, token, SWIGTYPE_p_std__mapT_std__pairT_std__string_std__string_t_std__vectorT_RsPhotoComment_t_t.getCPtr(comments));
  }

  public boolean submitAlbumDetails(SWIGTYPE_p_unsigned_int token, RsPhotoAlbum album) {
    return RetroshareJNI.RsPhoto_submitAlbumDetails(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), RsPhotoAlbum.getCPtr(album), album);
  }

  public boolean submitPhoto(SWIGTYPE_p_unsigned_int token, RsPhotoPhoto photo) {
    return RetroshareJNI.RsPhoto_submitPhoto(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), RsPhotoPhoto.getCPtr(photo), photo);
  }

  public boolean submitComment(SWIGTYPE_p_unsigned_int token, RsPhotoComment photo) {
    return RetroshareJNI.RsPhoto_submitComment(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), RsPhotoComment.getCPtr(photo), photo);
  }

  public boolean subscribeToAlbum(SWIGTYPE_p_unsigned_int token, SWIGTYPE_p_std__string grpId, boolean subscribe) {
    return RetroshareJNI.RsPhoto_subscribeToAlbum(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(token), SWIGTYPE_p_std__string.getCPtr(grpId), subscribe);
  }

  public boolean acknowledgeMsg(long token, SWIGTYPE_p_std__pairT_std__string_std__string_t msgId) {
    return RetroshareJNI.RsPhoto_acknowledgeMsg(swigCPtr, this, token, SWIGTYPE_p_std__pairT_std__string_std__string_t.getCPtr(msgId));
  }

  public boolean acknowledgeGrp(long token, SWIGTYPE_p_std__string grpId) {
    return RetroshareJNI.RsPhoto_acknowledgeGrp(swigCPtr, this, token, SWIGTYPE_p_std__string.getCPtr(grpId));
  }

}
