/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsPluginHashSetItem extends RsPluginItem {
  private long swigCPtr;

  protected RsPluginHashSetItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsPluginHashSetItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsPluginHashSetItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsPluginHashSetItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setHashes(RsTlvHashSet value) {
    RetroshareJNI.RsPluginHashSetItem_hashes_set(swigCPtr, this, RsTlvHashSet.getCPtr(value), value);
  }

  public RsTlvHashSet getHashes() {
    long cPtr = RetroshareJNI.RsPluginHashSetItem_hashes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvHashSet(cPtr, false);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream o, int arg1) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsPluginHashSetItem_print(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(o), arg1), false);
  }

}
