/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsPostedVote extends RsPostedMsg {
  private long swigCPtr;

  protected RsPostedVote(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsPostedVote_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsPostedVote obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsPostedVote(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsPostedVote() {
    this(RetroshareJNI.new_RsPostedVote(), true);
  }

}
