/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RsStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getOwnStatus(StatusInfo statusInfo) {
    return RetroshareJNI.RsStatus_getOwnStatus(swigCPtr, this, StatusInfo.getCPtr(statusInfo), statusInfo);
  }

  public boolean getStatusList(SWIGTYPE_p_std__listT_StatusInfo_t statusInfo) {
    return RetroshareJNI.RsStatus_getStatusList(swigCPtr, this, SWIGTYPE_p_std__listT_StatusInfo_t.getCPtr(statusInfo));
  }

  public boolean getStatus(SWIGTYPE_p_std__string id, StatusInfo statusInfo) {
    return RetroshareJNI.RsStatus_getStatus(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id), StatusInfo.getCPtr(statusInfo), statusInfo);
  }

  public boolean sendStatus(SWIGTYPE_p_std__string id, long status) {
    return RetroshareJNI.RsStatus_sendStatus(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(id), status);
  }

}
