/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsTlvKeyValue extends RsTlvItem {
  private long swigCPtr;

  protected RsTlvKeyValue(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsTlvKeyValue_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsTlvKeyValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsTlvKeyValue(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsTlvKeyValue() {
    this(RetroshareJNI.new_RsTlvKeyValue__SWIG_0(), true);
  }

  public RsTlvKeyValue(SWIGTYPE_p_std__string k, SWIGTYPE_p_std__string v) {
    this(RetroshareJNI.new_RsTlvKeyValue__SWIG_1(SWIGTYPE_p_std__string.getCPtr(k), SWIGTYPE_p_std__string.getCPtr(v)), true);
  }

  public long TlvSize() {
    return RetroshareJNI.RsTlvKeyValue_TlvSize(swigCPtr, this);
  }

  public void TlvClear() {
    RetroshareJNI.RsTlvKeyValue_TlvClear(swigCPtr, this);
  }

  public boolean SetTlv(SWIGTYPE_p_void data, long size, SWIGTYPE_p_unsigned_int offset) {
    return RetroshareJNI.RsTlvKeyValue_SetTlv(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), size, SWIGTYPE_p_unsigned_int.getCPtr(offset));
  }

  public boolean GetTlv(SWIGTYPE_p_void data, long size, SWIGTYPE_p_unsigned_int offset) {
    return RetroshareJNI.RsTlvKeyValue_GetTlv(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), size, SWIGTYPE_p_unsigned_int.getCPtr(offset));
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsTlvKeyValue_print(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public void setKey(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsTlvKeyValue_key_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getKey() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsTlvKeyValue_key_get(swigCPtr, this), true);
  }

  public void setValue(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsTlvKeyValue_value_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getValue() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsTlvKeyValue_value_get(swigCPtr, this), true);
  }

}
