/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsTlvKeySignatureSet extends RsTlvItem {
  private long swigCPtr;

  protected RsTlvKeySignatureSet(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsTlvKeySignatureSet_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsTlvKeySignatureSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsTlvKeySignatureSet(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsTlvKeySignatureSet() {
    this(RetroshareJNI.new_RsTlvKeySignatureSet(), true);
  }

  public long TlvSize() {
    return RetroshareJNI.RsTlvKeySignatureSet_TlvSize(swigCPtr, this);
  }

  public void TlvClear() {
    RetroshareJNI.RsTlvKeySignatureSet_TlvClear(swigCPtr, this);
  }

  public boolean SetTlv(SWIGTYPE_p_void data, long size, SWIGTYPE_p_unsigned_int offset) {
    return RetroshareJNI.RsTlvKeySignatureSet_SetTlv(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), size, SWIGTYPE_p_unsigned_int.getCPtr(offset));
  }

  public boolean GetTlv(SWIGTYPE_p_void data, long size, SWIGTYPE_p_unsigned_int offset) {
    return RetroshareJNI.RsTlvKeySignatureSet_GetTlv(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), size, SWIGTYPE_p_unsigned_int.getCPtr(offset));
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsTlvKeySignatureSet_print(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public void setKeySignSet(SWIGTYPE_p_std__mapT_unsigned_int_RsTlvKeySignature_t value) {
    RetroshareJNI.RsTlvKeySignatureSet_keySignSet_set(swigCPtr, this, SWIGTYPE_p_std__mapT_unsigned_int_RsTlvKeySignature_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__mapT_unsigned_int_RsTlvKeySignature_t getKeySignSet() {
    long cPtr = RetroshareJNI.RsTlvKeySignatureSet_keySignSet_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__mapT_unsigned_int_RsTlvKeySignature_t(cPtr, false);
  }

}
