/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsTlvBanList extends RsTlvItem {
  private long swigCPtr;

  protected RsTlvBanList(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsTlvBanList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsTlvBanList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsTlvBanList(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsTlvBanList() {
    this(RetroshareJNI.new_RsTlvBanList(), true);
  }

  public long TlvSize() {
    return RetroshareJNI.RsTlvBanList_TlvSize(swigCPtr, this);
  }

  public void TlvClear() {
    RetroshareJNI.RsTlvBanList_TlvClear(swigCPtr, this);
  }

  public boolean SetTlv(SWIGTYPE_p_void data, long size, SWIGTYPE_p_unsigned_int offset) {
    return RetroshareJNI.RsTlvBanList_SetTlv(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), size, SWIGTYPE_p_unsigned_int.getCPtr(offset));
  }

  public boolean GetTlv(SWIGTYPE_p_void data, long size, SWIGTYPE_p_unsigned_int offset) {
    return RetroshareJNI.RsTlvBanList_GetTlv(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), size, SWIGTYPE_p_unsigned_int.getCPtr(offset));
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsTlvBanList_print(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public void setEntries(SWIGTYPE_p_std__listT_RsTlvBanListEntry_t value) {
    RetroshareJNI.RsTlvBanList_entries_set(swigCPtr, this, SWIGTYPE_p_std__listT_RsTlvBanListEntry_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_RsTlvBanListEntry_t getEntries() {
    long cPtr = RetroshareJNI.RsTlvBanList_entries_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__listT_RsTlvBanListEntry_t(cPtr, false);
  }

}
