/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsTlvFileItem extends RsTlvItem {
  private long swigCPtr;

  protected RsTlvFileItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsTlvFileItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsTlvFileItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsTlvFileItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RsTlvFileItem() {
    this(RetroshareJNI.new_RsTlvFileItem(), true);
  }

  public long TlvSize() {
    return RetroshareJNI.RsTlvFileItem_TlvSize(swigCPtr, this);
  }

  public void TlvClear() {
    RetroshareJNI.RsTlvFileItem_TlvClear(swigCPtr, this);
  }

  public boolean SetTlv(SWIGTYPE_p_void data, long size, SWIGTYPE_p_unsigned_int offset) {
    return RetroshareJNI.RsTlvFileItem_SetTlv(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), size, SWIGTYPE_p_unsigned_int.getCPtr(offset));
  }

  public boolean GetTlv(SWIGTYPE_p_void data, long size, SWIGTYPE_p_unsigned_int offset) {
    return RetroshareJNI.RsTlvFileItem_GetTlv(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), size, SWIGTYPE_p_unsigned_int.getCPtr(offset));
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream out, int indent) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsTlvFileItem_print(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out), indent), false);
  }

  public void setFilesize(java.math.BigInteger value) {
    RetroshareJNI.RsTlvFileItem_filesize_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getFilesize() {
    return RetroshareJNI.RsTlvFileItem_filesize_get(swigCPtr, this);
  }

  public void setHash(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsTlvFileItem_hash_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getHash() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsTlvFileItem_hash_get(swigCPtr, this), true);
  }

  public void setName(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsTlvFileItem_name_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getName() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsTlvFileItem_name_get(swigCPtr, this), true);
  }

  public void setPath(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsTlvFileItem_path_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getPath() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsTlvFileItem_path_get(swigCPtr, this), true);
  }

  public void setPop(long value) {
    RetroshareJNI.RsTlvFileItem_pop_set(swigCPtr, this, value);
  }

  public long getPop() {
    return RetroshareJNI.RsTlvFileItem_pop_get(swigCPtr, this);
  }

  public void setAge(long value) {
    RetroshareJNI.RsTlvFileItem_age_set(swigCPtr, this, value);
  }

  public long getAge() {
    return RetroshareJNI.RsTlvFileItem_age_get(swigCPtr, this);
  }

  public void setPiecesize(long value) {
    RetroshareJNI.RsTlvFileItem_piecesize_set(swigCPtr, this, value);
  }

  public long getPiecesize() {
    return RetroshareJNI.RsTlvFileItem_piecesize_get(swigCPtr, this);
  }

  public void setHashset(RsTlvHashSet value) {
    RetroshareJNI.RsTlvFileItem_hashset_set(swigCPtr, this, RsTlvHashSet.getCPtr(value), value);
  }

  public RsTlvHashSet getHashset() {
    long cPtr = RetroshareJNI.RsTlvFileItem_hashset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTlvHashSet(cPtr, false);
  }

}
