/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsTurtleItem extends RsItem {
  private long swigCPtr;

  protected RsTurtleItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsTurtleItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsTurtleItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsTurtleItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean serialize(SWIGTYPE_p_void data, SWIGTYPE_p_unsigned_int size) {
    return RetroshareJNI.RsTurtleItem_serialize(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_unsigned_int.getCPtr(size));
  }

  public long serial_size() {
    return RetroshareJNI.RsTurtleItem_serial_size(swigCPtr, this);
  }

  public void clear() {
    RetroshareJNI.RsTurtleItem_clear(swigCPtr, this);
  }

}
