/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class RsTunnelHandshakeItem extends RsTunnelItem {
  private long swigCPtr;

  protected RsTunnelHandshakeItem(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.RsTunnelHandshakeItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RsTunnelHandshakeItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_RsTunnelHandshakeItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static RsTunnelHandshakeItem deserialise(SWIGTYPE_p_void data, long size) {
    long cPtr = RetroshareJNI.RsTunnelHandshakeItem_deserialise(SWIGTYPE_p_void.getCPtr(data), size);
    return (cPtr == 0) ? null : new RsTunnelHandshakeItem(cPtr, false);
  }

  public void setSourcePeerId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsTunnelHandshakeItem_sourcePeerId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getSourcePeerId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsTunnelHandshakeItem_sourcePeerId_get(swigCPtr, this), true);
  }

  public void setRelayPeerId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsTunnelHandshakeItem_relayPeerId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getRelayPeerId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsTunnelHandshakeItem_relayPeerId_get(swigCPtr, this), true);
  }

  public void setDestPeerId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsTunnelHandshakeItem_destPeerId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getDestPeerId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsTunnelHandshakeItem_destPeerId_get(swigCPtr, this), true);
  }

  public void setSslCertPEM(SWIGTYPE_p_std__string value) {
    RetroshareJNI.RsTunnelHandshakeItem_sslCertPEM_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getSslCertPEM() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.RsTunnelHandshakeItem_sslCertPEM_get(swigCPtr, this), true);
  }

  public void setConnection_accepted(long value) {
    RetroshareJNI.RsTunnelHandshakeItem_connection_accepted_set(swigCPtr, this, value);
  }

  public long getConnection_accepted() {
    return RetroshareJNI.RsTunnelHandshakeItem_connection_accepted_get(swigCPtr, this);
  }

  public SWIGTYPE_p_std__ostream print(SWIGTYPE_p_std__ostream o, int arg1) {
    return new SWIGTYPE_p_std__ostream(RetroshareJNI.RsTunnelHandshakeItem_print(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(o), arg1), false);
  }

  public boolean serialize(SWIGTYPE_p_void data, SWIGTYPE_p_unsigned_int size) {
    return RetroshareJNI.RsTunnelHandshakeItem_serialize(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_unsigned_int.getCPtr(size));
  }

  public long serial_size() {
    return RetroshareJNI.RsTunnelHandshakeItem_serial_size(swigCPtr, this);
  }

}
