/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class SharedDirInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SharedDirInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SharedDirInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_SharedDirInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFilename(SWIGTYPE_p_std__string value) {
    RetroshareJNI.SharedDirInfo_filename_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getFilename() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.SharedDirInfo_filename_get(swigCPtr, this), true);
  }

  public void setVirtualname(SWIGTYPE_p_std__string value) {
    RetroshareJNI.SharedDirInfo_virtualname_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getVirtualname() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.SharedDirInfo_virtualname_get(swigCPtr, this), true);
  }

  public void setShareflags(SWIGTYPE_p_t_RsFlags32T_0x184738_t value) {
    RetroshareJNI.SharedDirInfo_shareflags_set(swigCPtr, this, SWIGTYPE_p_t_RsFlags32T_0x184738_t.getCPtr(value));
  }

  public SWIGTYPE_p_t_RsFlags32T_0x184738_t getShareflags() {
    long cPtr = RetroshareJNI.SharedDirInfo_shareflags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_t_RsFlags32T_0x184738_t(cPtr, false);
  }

  public void setParent_groups(SWIGTYPE_p_std__listT_std__string_t value) {
    RetroshareJNI.SharedDirInfo_parent_groups_set(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_std__string_t getParent_groups() {
    return new SWIGTYPE_p_std__listT_std__string_t(RetroshareJNI.SharedDirInfo_parent_groups_get(swigCPtr, this), true);
  }

  public SharedDirInfo() {
    this(RetroshareJNI.new_SharedDirInfo(), true);
  }

}
