/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class SizeExpression {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SizeExpression(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SizeExpression obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_SizeExpression(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SizeExpression(RelOperator op, int v) {
    this(RetroshareJNI.new_SizeExpression__SWIG_0(op.swigValue(), v), true);
  }

  public SizeExpression(RelOperator op, int lv, int hv) {
    this(RetroshareJNI.new_SizeExpression__SWIG_1(op.swigValue(), lv, hv), true);
  }

  public boolean eval(FileEntry file) {
    return RetroshareJNI.SizeExpression_eval(swigCPtr, this, FileEntry.getCPtr(file), file);
  }

  public void linearize(LinearizedExpression e) {
    RetroshareJNI.SizeExpression_linearize(swigCPtr, this, LinearizedExpression.getCPtr(e), e);
  }

}
