/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class sslcert {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected sslcert(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sslcert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_sslcert(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sslcert(SWIGTYPE_p_X509 x509, SWIGTYPE_p_std__string id) {
    this(RetroshareJNI.new_sslcert__SWIG_0(SWIGTYPE_p_X509.getCPtr(x509), SWIGTYPE_p_std__string.getCPtr(id)), true);
  }

  public sslcert() {
    this(RetroshareJNI.new_sslcert__SWIG_1(), true);
  }

  public void setId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.sslcert_id_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.sslcert_id_get(swigCPtr, this), true);
  }

  public void setName(SWIGTYPE_p_std__string value) {
    RetroshareJNI.sslcert_name_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getName() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.sslcert_name_get(swigCPtr, this), true);
  }

  public void setLocation(SWIGTYPE_p_std__string value) {
    RetroshareJNI.sslcert_location_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getLocation() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.sslcert_location_get(swigCPtr, this), true);
  }

  public void setOrg(SWIGTYPE_p_std__string value) {
    RetroshareJNI.sslcert_org_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getOrg() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.sslcert_org_get(swigCPtr, this), true);
  }

  public void setEmail(SWIGTYPE_p_std__string value) {
    RetroshareJNI.sslcert_email_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getEmail() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.sslcert_email_get(swigCPtr, this), true);
  }

  public void setIssuer(SWIGTYPE_p_std__string value) {
    RetroshareJNI.sslcert_issuer_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getIssuer() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.sslcert_issuer_get(swigCPtr, this), true);
  }

  public void setFpr(SWIGTYPE_p_std__string value) {
    RetroshareJNI.sslcert_fpr_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getFpr() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.sslcert_fpr_get(swigCPtr, this), true);
  }

  public void setAuthed(boolean value) {
    RetroshareJNI.sslcert_authed_set(swigCPtr, this, value);
  }

  public boolean getAuthed() {
    return RetroshareJNI.sslcert_authed_get(swigCPtr, this);
  }

  public void setCertificate(SWIGTYPE_p_X509 value) {
    RetroshareJNI.sslcert_certificate_set(swigCPtr, this, SWIGTYPE_p_X509.getCPtr(value));
  }

  public SWIGTYPE_p_X509 getCertificate() {
    long cPtr = RetroshareJNI.sslcert_certificate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_X509(cPtr, false);
  }

}
