/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class StringExpression extends Expression {
  private long swigCPtr;

  protected StringExpression(long cPtr, boolean cMemoryOwn) {
    super(RetroshareJNI.StringExpression_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringExpression obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_StringExpression(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void linearize(LinearizedExpression e) {
    RetroshareJNI.StringExpression_linearize(swigCPtr, this, LinearizedExpression.getCPtr(e), e);
  }

}
