/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public final class StringOperator {
  public final static StringOperator ContainsAnyStrings = new StringOperator("ContainsAnyStrings", RetroshareJNI.ContainsAnyStrings_get());
  public final static StringOperator ContainsAllStrings = new StringOperator("ContainsAllStrings", RetroshareJNI.ContainsAllStrings_get());
  public final static StringOperator EqualsString = new StringOperator("EqualsString", RetroshareJNI.EqualsString_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static StringOperator swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + StringOperator.class + " with value " + swigValue);
  }

  private StringOperator(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private StringOperator(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private StringOperator(String swigName, StringOperator swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static StringOperator[] swigValues = { ContainsAnyStrings, ContainsAllStrings, EqualsString };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

