/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class TurtleHashInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TurtleHashInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TurtleHashInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_TurtleHashInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTunnels(SWIGTYPE_p_std__vectorT_unsigned_int_t value) {
    RetroshareJNI.TurtleHashInfo_tunnels_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_unsigned_int_t getTunnels() {
    return new SWIGTYPE_p_std__vectorT_unsigned_int_t(RetroshareJNI.TurtleHashInfo_tunnels_get(swigCPtr, this), true);
  }

  public void setLast_request(long value) {
    RetroshareJNI.TurtleHashInfo_last_request_set(swigCPtr, this, value);
  }

  public long getLast_request() {
    return RetroshareJNI.TurtleHashInfo_last_request_get(swigCPtr, this);
  }

  public void setLast_digg_time(SWIGTYPE_p_time_t value) {
    RetroshareJNI.TurtleHashInfo_last_digg_time_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getLast_digg_time() {
    return new SWIGTYPE_p_time_t(RetroshareJNI.TurtleHashInfo_last_digg_time_get(swigCPtr, this), true);
  }

  public void setService(RsTurtleClientService value) {
    RetroshareJNI.TurtleHashInfo_service_set(swigCPtr, this, RsTurtleClientService.getCPtr(value), value);
  }

  public RsTurtleClientService getService() {
    long cPtr = RetroshareJNI.TurtleHashInfo_service_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RsTurtleClientService(cPtr, false);
  }

  public TurtleHashInfo() {
    this(RetroshareJNI.new_TurtleHashInfo(), true);
  }

}
