/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class TurtleTunnel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TurtleTunnel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TurtleTunnel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_TurtleTunnel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLocal_src(SWIGTYPE_p_std__string value) {
    RetroshareJNI.TurtleTunnel_local_src_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getLocal_src() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.TurtleTunnel_local_src_get(swigCPtr, this), true);
  }

  public void setLocal_dst(SWIGTYPE_p_std__string value) {
    RetroshareJNI.TurtleTunnel_local_dst_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getLocal_dst() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.TurtleTunnel_local_dst_get(swigCPtr, this), true);
  }

  public void setTime_stamp(long value) {
    RetroshareJNI.TurtleTunnel_time_stamp_set(swigCPtr, this, value);
  }

  public long getTime_stamp() {
    return RetroshareJNI.TurtleTunnel_time_stamp_get(swigCPtr, this);
  }

  public void setTransfered_bytes(long value) {
    RetroshareJNI.TurtleTunnel_transfered_bytes_set(swigCPtr, this, value);
  }

  public long getTransfered_bytes() {
    return RetroshareJNI.TurtleTunnel_transfered_bytes_get(swigCPtr, this);
  }

  public void setSpeed_Bps(float value) {
    RetroshareJNI.TurtleTunnel_speed_Bps_set(swigCPtr, this, value);
  }

  public float getSpeed_Bps() {
    return RetroshareJNI.TurtleTunnel_speed_Bps_get(swigCPtr, this);
  }

  public void setHash(SWIGTYPE_p_std__string value) {
    RetroshareJNI.TurtleTunnel_hash_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getHash() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.TurtleTunnel_hash_get(swigCPtr, this), true);
  }

  public void setVpid(SWIGTYPE_p_std__string value) {
    RetroshareJNI.TurtleTunnel_vpid_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getVpid() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.TurtleTunnel_vpid_get(swigCPtr, this), true);
  }

  public TurtleTunnel() {
    this(RetroshareJNI.new_TurtleTunnel(), true);
  }

}
