/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class zcLocationResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zcLocationResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zcLocationResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_zcLocationResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public zcLocationResult() {
    this(RetroshareJNI.new_zcLocationResult__SWIG_0(), true);
  }

  public zcLocationResult(SWIGTYPE_p_std__string _gpgId, SWIGTYPE_p_std__string _sslId) {
    this(RetroshareJNI.new_zcLocationResult__SWIG_1(SWIGTYPE_p_std__string.getCPtr(_gpgId), SWIGTYPE_p_std__string.getCPtr(_sslId)), true);
  }

  public void setGpgId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.zcLocationResult_gpgId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getGpgId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.zcLocationResult_gpgId_get(swigCPtr, this), true);
  }

  public void setSslId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.zcLocationResult_sslId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getSslId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.zcLocationResult_sslId_get(swigCPtr, this), true);
  }

}
