/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.retroshare;

public class zcResolveResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zcResolveResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zcResolveResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RetroshareJNI.delete_zcResolveResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public zcResolveResult() {
    this(RetroshareJNI.new_zcResolveResult(), true);
  }

  public void setFlags(SWIGTYPE_p_DNSServiceFlags value) {
    RetroshareJNI.zcResolveResult_flags_set(swigCPtr, this, SWIGTYPE_p_DNSServiceFlags.getCPtr(value));
  }

  public SWIGTYPE_p_DNSServiceFlags getFlags() {
    return new SWIGTYPE_p_DNSServiceFlags(RetroshareJNI.zcResolveResult_flags_get(swigCPtr, this), true);
  }

  public void setInterfaceIndex(long value) {
    RetroshareJNI.zcResolveResult_interfaceIndex_set(swigCPtr, this, value);
  }

  public long getInterfaceIndex() {
    return RetroshareJNI.zcResolveResult_interfaceIndex_get(swigCPtr, this);
  }

  public void setFullname(SWIGTYPE_p_std__string value) {
    RetroshareJNI.zcResolveResult_fullname_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getFullname() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.zcResolveResult_fullname_get(swigCPtr, this), true);
  }

  public void setHosttarget(SWIGTYPE_p_std__string value) {
    RetroshareJNI.zcResolveResult_hosttarget_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getHosttarget() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.zcResolveResult_hosttarget_get(swigCPtr, this), true);
  }

  public void setPort(int value) {
    RetroshareJNI.zcResolveResult_port_set(swigCPtr, this, value);
  }

  public int getPort() {
    return RetroshareJNI.zcResolveResult_port_get(swigCPtr, this);
  }

  public void setTxtLen(int value) {
    RetroshareJNI.zcResolveResult_txtLen_set(swigCPtr, this, value);
  }

  public int getTxtLen() {
    return RetroshareJNI.zcResolveResult_txtLen_get(swigCPtr, this);
  }

  public void setGpgId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.zcResolveResult_gpgId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getGpgId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.zcResolveResult_gpgId_get(swigCPtr, this), true);
  }

  public void setSslId(SWIGTYPE_p_std__string value) {
    RetroshareJNI.zcResolveResult_sslId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getSslId() {
    return new SWIGTYPE_p_std__string(RetroshareJNI.zcResolveResult_sslId_get(swigCPtr, this), true);
  }

}
